### ISSUE TITLE
[BUG] my 15 map arts got swallowed by lagmc

### ISSUE THREAD

**Issue by barbasmas** [EarthMC/Issue-Tracker#1163] opened 2020-06-15 14:54 UTC
**Towny**

**My Map Arts disappeared/got replaced by other ones**
During the start of June 2020 I was working on 15 traffic map arts on a canvas in Madagascar. I locked all in the cartography and made copies in frames and chests. Today, 15th of June, I see that all my map arts are gone/replaced by other map arts/blank. I'm making a Ticket on emc support in hope that they can rollback or something.

**To Reproduce**
1. make map art
2. lock it in cartography table
3. Lagmc does its work
4. ur map arts are pooped

I want my map arts back i spent way too many hours on those

**Screenshots**
My finished map arts before Bug 11th of June
![2020-06-11_23 03 10](https://user-images.githubusercontent.com/65195596/84671069-34a47580-af27-11ea-9fc6-04a0e13c96d6.png)

My map arts after bug four days later 15th of June
![2020-06-15_16 30 10](https://user-images.githubusercontent.com/65195596/84671129-46861880-af27-11ea-86ae-4ff0d40c0d58.png)

I checked another wall where we put my map arts up and same there. Im holding a map art from my chest thats now blank. 15th of June
![2020-06-15_16 24 49](https://user-images.githubusercontent.com/65195596/84671166-53a30780-af27-11ea-9e42-e647cf05c63f.png)

**Additional context**
My IGN is Barbasmas and my discord is barbasmas#1737

**Comment by jkmartindale** [comment] 2020-06-17 05:42
#978 had the same error, sucks that the issue is still around

**Comment by barbasmas** [comment] 2020-06-17 05:49
ye i read it but the person there was lucky enough to be given safe copies of it by someone else... all mine were oof’ed and the aformentioned didnt get a solut

**Comment by barbasmas** [comment] 2020-06-17 05:53
i accidentally closed the issue... oops still new to github ^

ya i read that thread but the guy was lucky enough that someone else had safe copies. A mod said they are looking into it so i hope they can use worldedit, rollback or something else to quickly plop them back...

**Comment by jkmartindale** [comment] 2020-06-17 05:54
afaik the map arts are still there, they're just not displaying because of a chunk entity limit or something

**Comment by FutureLemon** [comment] 2020-06-18 05:06
I had a huge map of my whole nation go OOF it's over 10x10 I think

**Comment by KarlOfDuty** [comment] 2021-02-07 13:16
Hopefully fixed now with the new server version.

**Closed by KarlOfDuty** 2021-02-07 13:16 UTC
