### ISSUE TITLE
[BUG] Leads

### ISSUE THREAD

**Issue by MarkusAurelius124** [EarthMC/Issue-Tracker#191] opened 2018-11-29 14:50 UTC
**Server**
Terra Nova

**Describe the bug**
Not sure if bug but leads absolutely do not work properly on land, you cant drag the animals anymore you can only wait for it to want to move, then it'll move the way leads take it, but its still super slow.

**To Reproduce**
1. Get animal
2. Try to lead it
3. Ye

**Expected behavior**
Well if its a bug then, a fix I imagine.

**Comment by BennyBurst** [comment] 2018-11-29 17:09
I have been having the same issue. Had to use lead, and whatever food the animal desire

**Comment by MSatrokrm** [comment] 2018-11-29 17:11
leads on a laggy server = not a very fun time

**Comment by KarlOfDuty** [comment] 2019-03-05 00:27
Closed as this is most likely caused by lag.

**Closed by KarlOfDuty** 2019-03-05 00:27 UTC
Labels: Bug, EarthMC
