### ISSUE TITLE
Problem with town

### ISSUE THREAD

**Issue by Mixse** [EarthMC/Issue-Tracker#571] opened 2019-05-26 09:14 UTC
I can not manage my city although I am its owner, 
![Screenshot_1](https://user-images.githubusercontent.com/51045919/58379685-b12c8500-7faf-11e9-8cac-17fad3304e72.png)
In chat even not written that this I in this town of
![Screenshot_2](https://user-images.githubusercontent.com/51045919/58379692-bc7fb080-7faf-11e9-8459-2028a05f41a5.png)
But at the same time I can build and use different things in the town

**Comment by FutureCW** [comment] 2019-05-26 14:49
The game glitches and doesn’t show your tags sometimes. If you enter a nether portal it’ll fix it

**Comment by DasCodes** [comment] 2019-05-27 05:32
Duplicate of #518.

**Closed by DasCodes** 2019-05-27 05:32 UTC
Labels: Duplicate
