### ISSUE TITLE
pvp in towns

### ISSUE THREAD

**Issue by sawyerc18** [EarthMC/Issue-Tracker#362] opened 2019-02-13 03:17 UTC
when players start to pvp, if one is losing they either tend to log out or run into towns where pvp is disabled. the logging out is easily fixable with a plugin. i think that if 2 players are pvping, then one runs inside a town where pvp is disabled, they should still be able to pvp. note that players who have not initiated pvp (ie hit someone) still can be attacked in the non pvp areas, just the people who have engaged in pvp.

**Comment by cat234** [comment] 2019-02-16 05:44
Uh... no

**Comment by Pengun78** [comment] 2019-02-16 09:58
Pvp should be enabled in towns when the war plugin is there and nations declare war on each other

**Comment by cat234** [comment] 2019-02-16 17:51
Yes, and make it to where the residents can't attack each other during said war.

**Comment by KarlOfDuty** [comment] 2019-03-23 16:43
Duplicate of #432

**Closed by KarlOfDuty** 2019-03-23 16:43 UTC
Labels: Duplicate, EarthMC, Game Mechanic, New Plugin
