### ISSUE TITLE
[Plugin] HorseTpWithMe

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1443] opened 2021-12-09 03:35 UTC
### Is your feature request related to a problem? Please describe.

If you're sitting on a horse, pig, etc., and you decide to teleport you get teleported and your poor horse, pig, etc. is left behind. How could you do that to your dear horse?

### Describe the solution you'd like

The [HorseTpWithMe](https://www.spigotmc.org/resources/horsetpwithme.8186/) plugin allows players to teleport with whatever animal they're riding with several configurable options, see [here](https://www.spigotmc.org/resources/horsetpwithme.8186/#:~:text=Permissions%3A,not%20mentioned%20here.). Imagine being able to teleport and explore riding your house without having to travel far distances back and forth.

**Comment by alekb1** [comment] 2021-12-09 08:12
Duplicate of this:
https://github.com/EarthMC/Issue-Tracker/issues/1395

**Comment by Warriorrrr** [comment] 2022-01-10 09:09
Duplicate of #1395

**Closed by Warriorrrr** 2022-01-10 09:09 UTC
