### ISSUE TITLE
Conduits Missing in Aurora

### ISSUE THREAD

**Issue by wickz5** [EarthMC/Issue-Tracker#1623] opened 2023-01-16 09:17 UTC
There is no way to get Heart of the sea and without it we cannot make conduits which we need for our products. Even its in fishing treasure list its not something considered as rare given the current state of aurora. please consider. Thanks.

**Comment by Warriorrrr** [comment] 2023-02-25 11:03
Duplicate of #1604

**Closed by Warriorrrr** 2023-02-25 11:03 UTC
