### ISSUE TITLE
[BUG] /f checkpoint

### ISSUE THREAD

**Issue by henry-anderson** [EarthMC/Issue-Tracker#674] opened 2019-07-29 04:04 UTC
Server: Factions

When the server restarts your faction's checkpoint is removed and you have to set it again. /f checkpoint also threw an exception when I tried to use it the other day after a server restart. "An internal server error occurred." Another issue with this command is that teleporting only sometimes works. I have to use the command "/f checkpoint" 3-4 times before it actually teleports me after the 10 seconds are up.

The first problem about faction checkpoints being saved is a result of a bug in SavageFactions. Probably storing the checkpoint location in memory instead of serializing it. See the review [here](https://www.spigotmc.org/resources/savagefactions-the-ultimate-factions-plugin-1-8-1-14-2-0-beta-released.52891/reviews?page=4) by FyFou57.

**Comment by AlphaiaCP** [comment] 2019-08-05 17:08
Please update to https://www.spigotmc.org/resources/savagefactions-the-ultimate-factions-plugin-1-8-1-14-2-0-beta-released.52891/reviews?page=4

**Comment by KarlOfDuty** [comment] 2019-08-05 18:11
As I told you in your support ticket, we are already using the latest version.

**Comment by KarlOfDuty** [comment] 2019-08-12 04:35
Duplicate of #688

**Closed by KarlOfDuty** 2019-08-12 04:35 UTC
Labels: Bug, EarthMC: Factions, Factions
