### ISSUE TITLE
[BUG] fix jails

### ISSUE THREAD

**Issue by Pengun78** [EarthMC/Issue-Tracker#430] opened 2019-03-20 18:04 UTC
as i cant make tickets ill ask here
fix jails plox they get spawned outside
sometimes u gotta jail bad poopers

**Comment by drew8716** [comment] 2019-03-21 11:37
I ask to get jailed from multiple nations, was outlawed and was killed multiple times and I didn't even spawn in the jail they set up, I spawned at my regular bed.

**Comment by Pengun78** [comment] 2019-03-21 16:54
Exactly, ppl that get jailed spawn completely somewhere else in ur town

**Comment by Aitonater** [comment] 2019-03-21 23:12
Karl has said before jails will never be implemented because mods cannot access the commands i.e. because they do not belong to the town and don't have the rank required. They are disabled to stop people abusing jails and trapping new players. If they were implemented fully you could trap all your residents and stop them from playing on the server and the mods wouldn't be able to stop you so they are never going to make them work. I don't have a quote but this is what karl has said in the past.

**Comment by Kyoris** [comment] 2019-03-21 23:35
They could easily add a rule to where you cannot trap players for no legitimate reason (eg killing people in the town/nation) and to have to give them a way to pay their way out with gold or otherwise

**Comment by Aitonater** [comment] 2019-03-21 23:39
> They could easily add a rule to where you cannot trap players for no legitimate reason (eg killing people in the town/nation or being an absolute fuck) and/or to have to give them a way to pay their way out with gold or otherwise

The issue is not the legitimacy or need for trapping people. The issue is that no mods have access to jail permissions which is why they won't be implemented. It's been said by Karl the developer before. Even if you enable jails and people use them appropriately according to the rules against being overtly toxic etc... it would only take one town to abuse jails and trap players going against the rules and the mods wouldn't be able to free that player regardless as to whether or not the deserved to be in Jail for being a dick or not.

**Comment by Aitonater** [comment] 2019-03-21 23:44
> They could easily add a rule to where you cannot trap players for no legitimate reason (eg killing people in the town/nation or being an absolute fuck) and/or to have to give them a way to pay their way out with gold or otherwise

So you make this new rule. Jails have to be used appropriately. But how do you enforce it ? So a player reports the unfair use of  a jail to a mod. The mod sees screenshots or video evidence - yeah this player did nothing to deserve being jailed. But, the mod is actually powerless to free the person because of the way towny jails work and they are trapped there indefinitely.

**Comment by Pengun78** [comment] 2019-03-21 23:49
Except jails used to work fine on this server until one day it suddenly broke

**Comment by Aitonater** [comment] 2019-03-21 23:52
> Except jails used to work fine on this server until one day it suddenly broke

What Karl has said before is that mods cannot access the jail commands so they won't be implemented. Maybe that is why they "suddenly broke" maybe they were actually just disabled by Karl because mods could not access the comands they needed to enforce the servers rules.

**Comment by KarlOfDuty** [comment] 2019-03-23 16:04
As the comments here say, jails have been pretty broken for a long time which is why they are disabled.

**Comment by Aitonater** [comment] 2019-03-23 16:05
Boom told ya so.

**Closed by KarlOfDuty** 2019-03-23 16:04 UTC
Labels: EarthMC

**Comment by Pengun78** [comment] 2019-03-23 16:20
boom!!
