### ISSUE TITLE
[Bug] Item frames not rendering

### ISSUE THREAD

**Issue by 1lum1nat1** [EarthMC/Issue-Tracker#1867] opened 2024-09-06 11:46 UTC
### Server

Aurora

### Describe the bug

Wherever I am,the item frames are not rendered and I need to update them by hitting them,or rotating them,and it happens almost every time everywhere I am,it does not matter if the item frames are normal or glowing. But there are some exceptions,but they are random.

### To Reproduce

there are not any steps to produce the behavior,it just happens

### Expected behavior

I expected the item frames to render correctly

### Screenshots

![image](https://github.com/user-attachments/assets/cd83fbd0-0bdc-4335-ab50-a34e1da701e7)
![image](https://github.com/user-attachments/assets/bdd8dbb6-9803-40f2-9552-8eb64b297613)
![image](https://github.com/user-attachments/assets/94203f95-4e0e-41a1-a44c-0baa82c5355e)

**Comment by Warriorrrr** [comment] 2024-09-23 12:05
Does the map in the frame still show up when held? If not, this is a duplicate of #1834

**Comment by 1lum1nat1** [comment] 2024-10-01 21:37
It shows up

**Comment by 1lum1nat1** [comment] 2024-10-01 21:38
Oh.and,this happens when I put my shaders
![image](https://github.com/user-attachments/assets/8fb23d87-2d5e-4c50-8f16-826210b2d96a)

**Comment by 1lum1nat1** [comment] 2024-10-01 21:38
no wait nvm,it's the shaderpack

**Closed** 2024-10-05 15:38 UTC
Labels: Issue type: Bug
