### ISSUE TITLE
[BUG] /f perms does not work

### ISSUE THREAD

**Issue by AlphaiaCP** [EarthMC/Issue-Tracker#689] opened 2019-08-05 16:37 UTC
**Server**
Factions

**Describe the bug**
/f perms does not allow modifications of the faction permissions

**To Reproduce**
Steps to reproduce the behaviour:
Create / join a faction
Be leader / owner of the faction.
Run /f perms
Click on any icon
Nothing happens

**Expected behavior**
When you click on a button after running /f perms, a tiled display of Minecraft items appears standing for different options.

**Screenshots**
N/A

**Additional context**
This is urgent as factions can not cooperate with faction permissions not working.

Thanks

**Comment by docwhomc** [comment] 2019-08-07 22:26
My understanding is that this has been a known issue for a while.  Did no one ever make a ticket for it until now?

**Comment by docwhomc** [comment] 2019-08-07 23:04
Answering my question: https://github.com/EarthMC/Issue-Tracker/issues/650

**Comment by KarlOfDuty** [comment] 2019-08-12 04:32
Duplicate of #650

**Closed by KarlOfDuty** 2019-08-12 04:32 UTC
