### ISSUE TITLE
[Feature] Cobweb recipe

### ISSUE THREAD

**Issue by Pengun78** [EarthMC/Issue-Tracker#138] opened 2018-11-15 14:05 UTC
I think it would be cool if theres a cobweb recipe in Emc
there is currently no cobweb recipe in minecraft so i dont know how we should get cobwebs in emc
in the recipe there should be 5 string needed forming an X in the crafting table bar

**Comment by KarlOfDuty** [comment] 2018-11-28 17:59
Duplicate of #184

**Closed by KarlOfDuty** 2018-11-28 17:59 UTC
Labels: Duplicate
