### ISSUE TITLE
[Feature] Revert shake chance.

### ISSUE THREAD

**Issue by Fredeah** [EarthMC/Issue-Tracker#1361] opened 2021-06-01 08:47 UTC
To start off I’d firstly like to apologize for my poor English and secondly explain to everyone what shake is.
Shake is a Fishing ability in-game that comes with the mcMMO plugin. It is unlocked once the player hits level 150 in Fishing which lets them “fish” mob drops off mobs without having to kill the mob itself by casting a fishing rod at a mob and retracting it. Shake always deals 25% damage to the mob calculated off its total max health.

Now what is shaking like on the server? Shake used to be capped at a success rate of 56% at level 1000 fishing, meaning everytime you retracted your fishing rod off a mob there’d be a 56% chance of obtaining an item that the mob would normally drop after being killed. Until around a month and a half ago when the shake chance was suddenly nerfed beyond belief and set to 2% at all levels after being unlocked at level 150 fishing. This change came without notice and without any explanation the same time Acrobatics was enabled again, thus I believe the change was a mistake altogether as both Karl and Eagle didn’t seem to know much about the situation during two short conversations I had with them in-game.
To put the change in perspective, lets use a shaking a wither skeleton as an example:
According to the mcMMO wiki, whenever casting and retracting your rod off a wither skeleton and successfully shaking it, you’d have a 49% chance of receiving 1-3 pieces of coal, 50% chance of receiving a bone and a 1% chance of receiving a single wither skull. (Note that I do not have access to the server’s mcMMO config file thus the values for the drops could be incorrect) 
As long as my poor math is correct, this would mean that before the nerf whenever you retracted the rod off the skeleton you’d have a 0.56% total chance of receiving a wither skull. (56% x 1%). With the shaking chance success being lowered to 2%, the chance of receiving a wither skull whenever retracting your rod is a ridiculous 0.02%.

Please do not however only let those numbers blind you, as the requirements of even being able to shake a wither skeleton to begin with are some not many are able to meet, e.g: 
- Level 350 Alchemy for absorb potions, the materials for them and putting in the time for the long and painful task of mass brewing them (One splash absorb pot required for every time you hit the shake chance to avoid the 25% damage it inflicts, only 153 players can actually make absorb pots on the server as of right now)
- Level 1000+ Fishing to make it decently profitable timewise (In the past with 56% shake chance).
- Actually owning or having access to a wither skeleton (Personally I wouldn’t sell one for anything less than 2k gold, however seen some go for 500g in the past) and do keep in mind that new wither skeletons haven’t been naturally spawning in since before the nether reset unless I’m mistaken. Mob spawning was enabled last time for other “overworld mobs” back in February ish for a couple days.

Now to the dear admins of EMC, whether this nerf was intentional or not, I strongly believe shake should be reverted back to its former value. Shaking was one of the only decent ways to make profits aside from mining for gold when not taking passive methods into account such as running shops selling “non-mob items” or other services such as building and recruiting etc.

**Comment by gabeeebaby** [comment] 2021-06-01 17:04
It’s an issue with mcmmo itself, the server admins can’t do anything about it. The mcmmo dev was already told about it, but he seems to have gone inactive.

**Comment by yankees88888g** [comment] 2021-06-03 13:03
I think it's fine as is.

**Comment by KarlRaven06** [comment] 2021-06-07 18:20
not going to happen.  server got flooded with beacons and there are till hundreds of them saved up.  rarely are new ones being made because its not worth it.  prices are stable so no change should happen. do fix what isnt broken.  theres a crap ton of ways to make golds, withers arent the tops ones any more. 500gs an hour or more was way crazy

**Comment by Fredeah** [comment] 2021-06-09 22:53
> not going to happen. server got flooded with beacons and there are till hundreds of them saved up. rarely are new ones being made because its not worth it. prices are stable so no change should happen. do fix what isnt broken. theres a crap ton of ways to make golds, withers arent the tops ones any more. 500gs an hour or more was way crazy

You forgot to include that you're the one who owns the majority of these hundreds of saved up beacons

**Comment by Warriorrrr** [comment] 2021-06-17 17:28
Duplicate of #1343

**Closed by Warriorrrr** 2021-06-17 17:28 UTC
