### ISSUE TITLE
[Bug] I can't place levers horizontally.  

### ISSUE THREAD

**Issue by PoppyK** [EarthMC/Issue-Tracker#204] opened 2018-12-03 18:14 UTC
**Server**
EarthMC

**Describe the bug**
When I try placing levers, they don't lay horizontally, only vertically.  

**To Reproduce**

**Expected behavior**
Well in the past, you could place levers horizontally so I'm assuming this is just a bug.  

**Screenshots**
https://i.gyazo.com/2df35a8819091def007411f39b1c8e2d.png

**Additional context**

**Comment by KarlOfDuty** [comment] 2018-12-03 18:17
May be an issue with the experimental version of towny we are running.

**Comment by PoppyK** [comment] 2018-12-05 19:15
https://i.gyazo.com/5d458f08f8577f085278dbd5e1455fec.png
It happens both in and out of claims.

**Comment by BowShot118** [comment] 2018-12-05 19:21
I didn't think you could do that in normal minecraft without mods?

**Comment by osnapitzjamie** [comment] 2018-12-25 13:20
> I didn't think you could do that in normal minecraft without mods?

Correct.

https://minecraft.gamepedia.com/Lever#History

issue needs closing as its not a bug @KarlOfDuty

**Comment by KarlOfDuty** [comment] 2018-12-29 22:09
![image](https://user-images.githubusercontent.com/18099825/50542488-b03d2600-0bbe-11e9-8ccd-b2ceee557e38.png)
It is definitely a minecraft feature.

**Comment by KarlOfDuty** [comment] 2018-12-29 22:09
And it works for me on the server so not sure how to reproduce it.

**Closed** 2019-01-31 18:01 UTC
Labels: Bug, EarthMC
