### ISSUE TITLE
Head name bug

### ISSUE THREAD

**Issue by Ko-ha-ru** [EarthMC/Issue-Tracker#1869] opened 2024-09-13 14:47 UTC
### Server

Aurora

### Describe the bug

The names of the heads I had put before had been changed to " Head Database's Head" or "Player Head".

If you break the head you previously placed, it will be renamed to "Head Database's Head" or "Player Head".
It happened suddenly that I don't remember the details.

### Expected behavior

I want my heads back to their original names.

**Comment by Warriorrrr** [comment] 2024-09-21 20:14
Was this head placed for a longer time? I can't reproduce this when breaking a freshly placed head

**Comment by Veyronity** [comment] 2024-10-07 11:32
It was a bug temporarily, pretty sure it's fixed now

I would say it was there for a week max

**Comment by CorruptedGreed** [comment] 2024-11-22 03:49
Does not seem to happen anymore

**Closed by CorruptedGreed** 2024-11-22 03:49 UTC
Labels: Issue type: Bug, Status: Awaiting OP's Feedback
