### ISSUE TITLE
Add Queue System to Join the Server

### ISSUE THREAD

**Issue by Golurk1** [EarthMC/Issue-Tracker#177] opened 2018-11-25 18:46 UTC
Can a Queue system be added to the server? It's constantly full and often takes me like 10 minutes to join the server. I've seen other people deal with this issue too. I'm sure its also annoying to donators when they are constantly asked to leave so people can join. If you are going to privilege people who have money to spend on stuff like this, at least give those who don't a greater opportunity to even join the server.

**Comment by 32Gold** [comment] 2018-11-25 18:47
i agree

**Comment by KarlOfDuty** [comment] 2018-11-25 18:48
Duplicate of #70

**Closed by KarlOfDuty** 2018-11-25 18:48 UTC
Labels: Duplicate
