### ISSUE TITLE
Resource Pack Custom Item Texture Bug

### ISSUE THREAD

**Issue by MCPBuilderguy** [EarthMC/Issue-Tracker#1772] opened 2024-01-25 21:57 UTC
### Server

Aurora

### Describe the bug

ere is an issue regarding a feature that Optifine, as well as some other popular mods, use for resource packs called Custom Item Textures, or CIT for short. This feature allows tools, items, armor, and mobs to have custom textures based on their NBT data, such as name, lore, spawn location, etc.

This feature used to work fine on Aurora for the first few months but stopped sometime around late 2022. From the player's perspective, any CIT (Custom Item Texture) still works on mobs or when the item is on the player, held or worn by a mob, on the ground, or in an item frame. However, the CIT will not display when being held or worn by another player or armor stand.

I believe this issue is could be due to a change in an anti-cheat measures related to how certain data is passed between two players, due to how this feature still currently works fine in nova. Assuming it is the anti-cheat, I don't see any reason why these CIT features can't co-exist with modern EMC.

### To Reproduce

Using any resource pack that makes use of CIT while using popular mods such as Optifine or CIT resewn, you can very easily replicate this issue.

For an example: You can use EarthPack & try renaming diamond/netherite armor to Mark IV. You can expect the armor to then change texture based on said name.

[[EarthPack.zip](https://github.com/EarthMC/Issue-Tracker/files/13200694/EarthPack.zip)](https://github.com/EarthMC/Issue-Tracker/files/13200694/EarthPack.zip)

For another example: You can use this Sculk Armor Pack from Planet Minecraft & try renaming netherite armor to Sculk. You can expect the armor to then change texture.

https://www.planetminecraft.com/texture-pack/skulked-better-minimal-sculk-netherite-armor-cit/

However, neither of these armor textures will be visible to the player when it is either placed on an armor stand or worn by another player.

### Expected behavior

Players who are using the same resource pack to see each others textures will not be able to see said CIT when it is either held or worn by another player.

### Screenshots

The following photos are of me wearing then displaying the same named armor on an armor stand on Nova then on Aurora. The 

Armor will display its CIT correctly on Nova when it is held/worn by the player & also while it is held/worn by another player or armor stand.
![2023-10-29_22 06 08](https://github.com/EarthMC/Issue-Tracker/assets/57657611/88b75d05-0c9c-4f9c-8bc9-49811b907ec3)
![2023-10-29_22 06 32](https://github.com/EarthMC/Issue-Tracker/assets/57657611/9d4f1833-4eff-46f8-89c9-db6ae20d1a29)

However on Aurora CIT will only display correctly when in that players inventory & not on any other player or armor stand that has the same CIT item. 
![2023-10-29_22 01 58](https://github.com/EarthMC/Issue-Tracker/assets/57657611/bc1fd854-9267-4a1b-bd92-891b632f389a)
![2023-10-29_22 02 13](https://github.com/EarthMC/Issue-Tracker/assets/57657611/f5c9d1d8-bbc7-4d8a-a319-09ba6a2fec6a)

### Additional context

CIT are used by a decent portions of the EMC community. I myself run a CIT resource pack for EMC community submitted content to be added, that has gained several hundreds users over the last 2 years I've been managing it. In addition to other groups such as F1, Squid Games, Olympics, or Football leagues who use also use CIT Packs to make their events more engaging. I feel that these communities are substantial enough to not be overlooked. I thank you for your time & hope this issue can be resolved quickly.

**Comment by Aylywyn** [comment] 2024-01-25 22:04
Duplicate of #1725 by.... oh...

**Comment by MCPBuilderguy** [comment] 2024-01-25 22:27
It's been months with no response, figured it was ignored then buried.

> Duplicate of #1725 by.... oh...

**Comment by Warriorrrr** [comment] 2024-04-08 19:19
Still not a reason to open the same issue twice

**Closed by Warriorrrr** 2024-04-08 19:19 UTC
Labels: Issue type: Bug
