### ISSUE TITLE
Alcohol Plugin

### ISSUE THREAD

**Issue by LokiBeeper** [EarthMC/Issue-Tracker#1611] opened 2022-12-22 04:16 UTC
### Is your feature request related to a problem? Please describe.

a lack of Pubs or Alchohol in EarthMC

### Describe the solution you'd like

For there to be an Alcohol Plugin to be added to EarthMC since civilizations also ran on Alcohol

### Additional context

https://dev.bukkit.org/projects/brewery at this link is the alcohol   plugin i suggest for EMC to use but you can use others that are better if you would like.

**Comment by Warriorrrr** [comment] 2022-12-27 20:03
Duplicate of #817 and #287

**Closed by Warriorrrr** 2022-12-27 20:03 UTC
