### ISSUE TITLE
[Feature] [Aurora] Don't Allow Town Outlaws to Teleport in Outlawed Town

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1495] opened 2022-05-03 03:19 UTC
### Server

Towny

### Describe the bug

Outlaws shouldn't be able to teleport out of the outlawed towns they are in.

### To Reproduce

/t outlaw add Username
Have another player /t spawn in the outlaw town and they teleport.

### Expected behavior

Outlaw can't teleport in outlaw town

**Comment by Warriorrrr** [comment] 2022-05-05 12:41
This is not a bug, this was changed in order to prevent players from being trapped indefinitely by other players.

**Comment by Basically-Andrew** [comment] 2022-05-05 12:52
I understand not wanting players trapped indefinitely, but the rules still state trapping is allowed for a limited amount of time. Staff can always release someone if they're trapped indefinitely. I would like to now make this a suggestion to revert.

**Comment by Basically-Andrew** [comment] 2022-05-11 20:54
> This is not a bug, this was changed in order to prevent players from being trapped indefinitely by other players.

Would a /stuck command or similar not be a better working solution? Many factions servers allow players to do /stuck and wait 2-5mins without moving, attacking, etc. to be teleported away from an indefinite trap. This could also be added to Towny with all teleportation commands having a timer when in outlawed towns.

**Comment by RAWRyoutube** [comment] 2022-05-30 21:39
> I understand not wanting players trapped indefinitely, but the rules still state trapping is allowed for a limited amount of time. 

This sentence is fixed by doing no change. Players can still be trapped for limited amounts of time in the current method. Changing this would allow the possibility of much longer periods of time spent in traps, especially for those who do not know about the EarthMC Support discord.
It should be noted that changes from the current system would also cause an increase in ticket volume, and subsequently, possibly adding extra delays of time between submitting a ticket and getting action for all tickets.
There is no need to increase the powers of traps by changing something as pointless as this. It would only cause more harm to the server.

**Comment by CorruptedGreed** [comment] 2023-12-10 09:44
Will be pursued once some anti-stuck method is developed

**Closed by CorruptedGreed** 2023-12-10 09:44 UTC
Labels: Issue type: Game Mechanic, Issue type: Towny Plugin, Server: Aurora
