### ISSUE TITLE
[BUG] nation titles and ranks occasionally reset

### ISSUE THREAD

**Issue by TheSuperGamer20578** [EarthMC/Issue-Tracker#1297] opened 2021-01-07 23:32 UTC
### Server

towny

### Describe the bug

occasionally all the ranks, titles and surnames in our nation are reset

### To Reproduce

1. have titles, surnames or ranks in your nation
2. wait a random amount of time
3. it will all be gone

### Expected behavior

all titles, surnames and ranks stay the same

### Screenshots

what it ended up doing
![image](https://user-images.githubusercontent.com/30369708/103956406-8f8c0b80-519c-11eb-99a3-9fc62bffaaad.png)
what it should be
![image](https://user-images.githubusercontent.com/30369708/103956439-a2064500-519c-11eb-9438-6b970ad53981.png)
what I have to do occasionally to fix it
![image](https://user-images.githubusercontent.com/30369708/103956297-5fdd0380-519c-11eb-838c-07706555bff8.png)

**Comment by 10op10** [comment] 2021-01-07 23:36
I believe this is a bug within townys side not EMC

**Comment by Warriorrrr** [comment] 2021-01-08 00:18
Duplicate of #1286, I already commented there that this was fixed in Towny, the admins just need to update towny and this will be fixed

**Closed** 2021-01-23 17:42 UTC
Labels: Issue type: Bug
