### ISSUE TITLE
Silk touch on spawner did not give the spawner back

### ISSUE THREAD

**Issue by shelly222** [EarthMC/Issue-Tracker#976] opened 2020-02-28 22:15 UTC
**Server**
Towny

**Describe the bug**
I mined the blaze spawner with a silk touch pick, and it didnt give me back my spawner and blaze egg back like it use to be. 

**To Reproduce**
1. Go to your blaze spawner
2. Mine it with a silk touch pickaxe to get the spawner back so u can seel it or place it at an other spot.
3. See error : Even with silk touch you dont get it back like you are suppose to..
4. You just lost your spawnee

**Expected behavior**
You dont get the spawner and the blaze egg back as it always did before..

**Screenshots**
no screenshot, i got nothing back lol.

**Comment by QJWIN** [comment] 2020-03-02 15:25
Its not a bug .. like sign shop, the silk touch spawner plugin is actualy turned off no spawner back ...
untill they update the plugin ...

**Comment by DasCodes** [comment] 2020-03-11 11:58
This should be fixed.

**Closed by DasCodes** 2020-03-11 11:58 UTC
