### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CoffeeRelic7718** [EarthMC/Issue-Tracker#1393] opened 2021-08-26 22:03 UTC
### Server
EarthMC Main SErver

### Describe the bug
I accidentally pressed q and my Sword Glitched into the Ice

### To Reproduce
1. Throw Sword
2. Have It Glitch into the Ice
3. Watch it Despawn

### Expected behavior
The Sword to not glitch through the ice

### Screenshots

<img width="402" alt="Screen Shot 2021-08-26 at 6 01 17 PM" src="https://user-images.githubusercontent.com/89612724/131041917-78be369a-0ea1-4b82-adcb-cc238ed866de.png">

### Additional context
It was a God Netherite Sword

**Comment by Warriorrrr** [comment] 2021-08-29 21:36
Duplicate of #1387

**Closed by Warriorrrr** 2021-08-29 21:36 UTC
Labels: Issue type: Bug
