### ISSUE TITLE
Ores looks like stone[Bug]

### ISSUE THREAD

**Issue by Ultraokasan** [EarthMC/Issue-Tracker#1697] opened 2023-07-11 10:18 UTC
### Server

Aurora

### Describe the bug

Ores and bone blocks looks like stone, and only when you break them you can see if are ores.
Reported at ticket-41454.
It also happens to more players and to me:

https://github.com/EarthMC/Issue-Tracker/assets/128364522/2a7af586-edf5-4df5-96e4-f5092ec9e1c7

### To Reproduce

When you go mining you can see only plain stone and when you break that stone you can see that it was not stone, it was an ore. Also ores and bone blocks used as decorations looks like stone.

### Expected behavior

Ores looking like ores.

**Comment by nidomas** [comment] 2023-07-11 13:32
Yes, I am experiencing this as well, a lot of our builds use bone blocks and suddenly they all turned to stone, before they would turn to stone at around 50 blocks distance. I am assuming this is to do with the anti x-ray plugin. If possible maybe change it back to how it was before.

**Comment by HopelessSoap** [comment] 2023-07-11 20:11
I'm having the same issue (https://github.com/EarthMC/Issue-Tracker/issues/1696), I believe it is due to the anti-x-ray plugin in use, as others have said.

**Comment by Warriorrrr** [comment] 2023-07-16 09:19
Closing as a duplicate of #1666

**Closed by Warriorrrr** 2023-07-16 09:19 UTC
Labels: Issue type: Bug
