### ISSUE TITLE
[BUG] I was removed from my own town when I changed IGN

### ISSUE THREAD

**Issue by LittleTinyThingy** [EarthMC/Issue-Tracker#1024] opened 2020-03-23 17:59 UTC
After I changed my IGN I was removed from my town (which I own). My old name is still the baron of the town but I am removed from it. My town is Labinsk and my new IGN is Menuto. My old IGN was Metolazone. Here is proof that I own both of the names 
https://namemc.com/profile/Menuto.3

**Comment by jkmartindale** [comment] 2020-03-23 18:00
Possible duplicate of #1015

**Comment by Basically-Andrew** [comment] 2020-03-25 17:41
When was the last time you logged on to EarthMC? Towns kick out residents including mayors if they haven't been active in the past 42 days.

**Comment by PikachewFTW** [comment] 2020-03-26 05:44
I logged in 1-2 days before I changed my IGN. I assure you I was on very recently. Is there any way you can put me back in my town? My old IGN still says that its mayor btw.

**Comment by LittleTinyThingy** [comment] 2020-03-26 05:45
I was on a day or two before I was removed. My old IGN (Metolazone) still displays as the mayor of the town.

**Comment by KarlOfDuty** [comment] 2020-04-23 18:07
Can you check if it has been fixed?

**Comment by LittleTinyThingy** [comment] 2020-04-24 22:10
It still has not been resolved

**Closed** 2021-02-07 13:39 UTC
Labels: Issue type: Bug, Issue type: Towny Plugin, Server: Towny
