### ISSUE TITLE
 [Feature] warps upgrades

### ISSUE THREAD

**Issue by ArbiteRv** [EarthMC/Issue-Tracker#577] opened 2019-05-28 18:27 UTC
Give us stuff to spend gold on and add at least one warp.

**Comment by FutureLemon** [comment] 2019-05-28 19:46
Towny outposts or Factions warps? I like both of them, but be more clear to the staffteam.

**Comment by KarlOfDuty** [comment] 2019-12-04 00:45
Duplicate of #562

**Closed by KarlOfDuty** 2019-12-04 00:45 UTC
Labels: Server: Factions
