### ISSUE TITLE
[BUG] 32Doct_fr's data is not gone

### ISSUE THREAD

**Issue by Remis932** [EarthMC/Issue-Tracker#1007] opened 2020-03-17 22:13 UTC
**Server**
Towny
**Describe the bug**
It has been more than 42 days since 32Doct_fr was last seen online (The first of February, 1AM CET)
and his data has not been yet erased. This bug is causing high inactivity in Vietnam, which as you
may think, is VERY unwanted.

**To Reproduce**
You cannot reproduce this error, i mean, to see the error, just do /res 32Doct_fr and look at the time he was last seen online.

**Expected behavior**
I hope u guys just yeet his data already into the shadow realm.
**Screenshots**
no lol

**Additional context**

**Comment by jkmartindale** [comment] 2020-03-17 22:41
#1000

**Comment by Warriorrrr** [comment] 2020-03-17 23:08
This is not something for github, make a ticket on the support discord instead.

**Comment by Cactusinapumpkin** [comment] 2020-03-18 02:36
Usually it takes a little longer to account for server downtime. Just be patient

**Comment by Remis932** [comment] 2020-03-18 07:25
The server must have bedn down for about a week and a half in the 42 days
that doct has been banned.

**Comment by FutureLemon** [comment] 2020-03-18 13:49
It's fixed people lose their towny data again.

**Comment by docwhomc** [comment] 2020-03-19 02:10
@Warriorrrr this is a bug, bugs go on github.

**Comment by docwhomc** [comment] 2020-03-25 10:42
Duplicate of #1000.

**Closed by docwhomc** 2020-03-25 10:42 UTC
Labels: Rejected: Duplicate
