### ISSUE TITLE
Higher the rank, quicker to get into the server.

### ISSUE THREAD

**Issue by GetPrankedNerd** [EarthMC/Issue-Tracker#611] opened 2019-06-19 16:30 UTC
Waiting for the queue could be frustrating for people who are really devoted to spend a lot of their time on this server.

The purchasable ranks should go down the queue by rank priority. For example if a blue rank joins the queue, then it is first in line because it is the highest rank. Then purple is second, yellow is third, priority queue is forth, and the casual players would be last.

**Comment by FutureLemon** [comment] 2019-06-20 09:44
While it might be very frustrating you have to admit that it does make sense for people that paid more to the server would be put higher up in the queue.

**Comment by GetPrankedNerd** [comment] 2019-06-20 09:47
No I'm saying that all the ranks and queue priority are in the same priority queue. Like Blue rank won't got in front of priority queue.

**Comment by FutureLemon** [comment] 2019-06-20 17:50
Well why shouldn't it be put in front of you? They paid more than you.

**Comment by GetPrankedNerd** [comment] 2019-06-20 17:52
I still don't think you know what I'm trying to say. The people who pay more DON'T go in front of the other people. For example. Purple will not go in front of yellow even though Purple cost more than yellow.

**Comment by shirazmatas** [comment] 2019-06-20 18:15
This is a duplicate of #606

**Closed by shirazmatas** 2019-06-20 18:15 UTC
