### ISSUE TITLE
[Bug] Ore blocks that are exposed to air only appear when a block update occurs near them

### ISSUE THREAD

**Issue by HopelessSoap** [EarthMC/Issue-Tracker#1696] opened 2023-07-11 05:22 UTC
### Server

Aurora

### Describe the bug

Ore blocks appear to just be a stone block until a block update (i think) occurs within a few blocks from them, even if they are visible and exposed to air. I would guess that this is due to an anti-x-ray plugin hiding them, even though they are clearly visible without x-ray. But that is just complete speculation.

### To Reproduce

Find a cave; very few, if any, ores are visible. Start punching random blocks while walking through the cave. This should cause ores to suddenly appear near the player.

### Expected behavior

Any ore blocks that are exposed to air should always be visible.

### Screenshots

https://github.com/EarthMC/Issue-Tracker/assets/66231495/3c65a776-78a2-455b-87e6-4ccbd7805175

**Comment by HopelessSoap** [comment] 2023-07-11 05:25
The video didn't work
https://imgur.com/a/GhOizTf

**Comment by HopelessSoap** [comment] 2023-07-11 05:30
I was using a couple mods in that video (sodium, lithium, iris, indium, some more optimization stuff) but have confirmed that the issue occurs on vanilla minecraft as well

**Comment by Aylywyn** [comment] 2023-07-11 05:36
Will confirm earlier this evening while mining.  Also, the Bone Block to Stone bug.

Definitely related to some update of the Anti-X-Ray plugin.

**Comment by Warriorrrr** [comment] 2023-07-16 09:20
Closing as a duplicate of #1666

**Closed by Warriorrrr** 2023-07-16 09:20 UTC
Labels: Issue type: Bug
