### ISSUE TITLE
[Bug] Nova dynmap is denying to exist

### ISSUE THREAD

**Issue by UnitiveBog10934** [EarthMC/Issue-Tracker#1633] opened 2023-02-03 13:25 UTC
### Server

Nova

### Describe the bug

Nova dynmap doesnt seem to want to exist

(Restart nova)

### To Reproduce

Open this: https://earthmc.net/map/nova/
It aint working

### Expected behavior

To work and open the map

**Comment by Warriorrrr** [comment] 2023-02-03 15:18
Duplicate of #1632

**Closed by Warriorrrr** 2023-02-03 15:18 UTC
Labels: Issue type: Bug
