### ISSUE TITLE
Llamas

### ISSUE THREAD

**Issue by FurdenFuhrer** [EarthMC/Issue-Tracker#79] opened 2018-11-02 23:09 UTC
Make Llamas spawn in Savanna biomes

**Comment by KarlOfDuty** [comment] 2018-11-03 09:56
![image](https://user-images.githubusercontent.com/18099825/47950755-098a2f80-df57-11e8-90af-8b35458d67c3.png)
They already do?

**Comment by KarlOfDuty** [comment] 2018-11-04 06:16
Duplicate of #89

**Closed by KarlOfDuty** 2018-11-04 06:16 UTC
Labels: Duplicate, Needs Feedback
