### ISSUE TITLE
War Mechanic

### ISSUE THREAD

**Issue by DKS134** [EarthMC/Issue-Tracker#220] opened 2018-12-07 21:01 UTC
**Is your feature request related to a problem? Please describe.**
Yep, Qin raids everyone, no one can start a war and try to destroy their towns and get our stuff back

**Describe the solution you'd like**
Simple, war system, no matter from which plugin, can even be from towny, this is a request from most of the european nations, jevil kills everyone and we cant kill him and raid qin to get our stuff back

**Additional context**
Idk, most of the european nations are supporting this

**Comment by Pengun78** [comment] 2018-12-07 21:06
Yes please

**Comment by Pengun78** [comment] 2018-12-07 21:06
We should be able to annex land

**Comment by Pengun78** [comment] 2018-12-07 21:06
Well u can toggle options for wars like annex land on or off

**Comment by Pengun78** [comment] 2018-12-07 21:39
1 person can vote more than a 100 times on strawpoll

**Comment by SpookyScoops** [comment] 2018-12-08 00:04
Just give in to Qin already

**Comment by NigelFarage666** [comment] 2018-12-09 13:02
Please staff you did such a great  job with TN! 
Please fix this those guys keep attacking us and when we attack them they just hide in claimed land!
Its not nice!

**Comment by epicsans2003** [comment] 2018-12-09 16:32
I can agree.
There's not much you can do as you're probably going to get attacked when you're alone in the forest jacking off to some deers mating.

I must say tho it's pretty funny looking at the dynmap and then seeing Jevil sneaking up on someone. Even tho I warned the guy, it was too late and he still got killed.
Poor lad :(

**Comment by 4noah18** [comment] 2018-12-16 10:33
We've been waiting for a war plugin for months, please for the love of God. People can do whatever they want and then just run away to their safe area without any consequences. It's really annoying for the people who are raided and it makes you want to stop playing. I've been there myself before.

**Comment by KarlOfDuty** [comment] 2018-12-18 23:36
Duplicate of #201

**Closed by KarlOfDuty** 2018-12-18 23:36 UTC
Labels: Duplicate, EarthMC, New Feature
