### ISSUE TITLE
[BUG] Can't chat

### ISSUE THREAD

**Issue by Memetric** [EarthMC/Issue-Tracker#1359] opened 2021-05-20 02:20 UTC
### Server

EarthMC

### Describe the bug

Whenever I try to chat it throws an error and kicks me out.

### To Reproduce

1. chat
2. 
3. 

### Expected behavior

My message to appear in chat.

### Screenshots

![image](https://user-images.githubusercontent.com/51463559/118908971-5012c000-b8f0-11eb-8ca1-6b608fe3f210.png)

**Comment by Warriorrrr** [comment] 2021-05-20 08:34
Duplicate of #1358

**Closed by Warriorrrr** 2021-05-20 08:34 UTC
Labels: Issue type: Bug
