### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by volleyball4ever** [EarthMC/Issue-Tracker#1594] opened 2022-11-02 13:06 UTC
### Server

Aurora

### Describe the bug

Many times when i join the server im getting kicked from aurora for "timed out" after a few seconds of waiting with no ping
when that happens im trying to join aurora again and again and its always kicking me to the hub.
also when i can join the server my ping is very unstable and jumps to 10000 sometimes especially when im moving fast like with boat on ice or when im spawning in a new place.

### To Reproduce

it never happend to me in other servers
and it started since the last month or two months

### Expected behavior

i would like to know why is that happening and how can i fix that

### Screenshots

![2022-11-01_19 47 02](https://user-images.githubusercontent.com/60809646/199497030-9b5d84f2-9da8-42c7-b074-f462d92abcc5.png)

### Additional context

My IGN is volleyball4ever1

**Comment by asyi0** [comment] 2022-11-04 06:21
I'm not sure detail reason, but sometimes I also see this issue.
It seems often occur in Asia night time. 

I don't know the exact reason, but I often encounter this issue.
I think it happens more often during nighttime in Asia time zone when the number of players is higher.

**Comment by Warriorrrr** [comment] 2022-11-06 12:42
Closing as duplicate of #1593

**Closed by Warriorrrr** 2022-11-06 12:42 UTC
Labels: Issue type: Bug
