### ISSUE TITLE
combat logging

### ISSUE THREAD

**Issue by sawyerc18** [EarthMC/Issue-Tracker#354] opened 2019-02-08 15:22 UTC
i think that since this server has a bunch of pvp u should disable combat logging. if you are tagged in pvp or within 32 blocks of another player not in your town then you should leave a combat logger. i know there are already some great combat logger plugins for 1.13.2 that are compatible with towny.

**Comment by johnyuki** [comment] 2019-02-08 19:03
There is a really popular combat logging thing that lots of pvp servers use that adds in a "zombie" version of your character if you log out whilst in pvp, so that the attacking player can kill the zombie and still get your stuff. Just having that in the server would be good.

**Comment by KarlOfDuty** [comment] 2019-02-11 14:03
Duplicate of #278

**Closed by KarlOfDuty** 2019-02-11 14:03 UTC
