### ISSUE TITLE
Too close to neighboring town block to claim but also it makes no sense

### ISSUE THREAD

**Issue by Beaverman1** [EarthMC/Issue-Tracker#1101] opened 2020-05-08 12:45 UTC
**Server**
Towny

**Describe the bug**
I can't claim two plots at the coordinates -15192 -8134 and -15190 -8163 ... IT is in my ice boating course that I need to get done soon. It  doesn't make sense since there is a plot next to it just as close that I could claim. It says it's too close to another towns homeblock, please fix
![2020-05-08_07 44 49](https://user-images.githubusercontent.com/65022699/81406779-d43c4000-90ff-11ea-9dd8-ee7138ad8a80.png)

**Additional context**
I really need this fixed as I have a race in a few weeks

**Comment by jkmartindale** [comment] 2020-05-08 16:20
You're not the only one, see also #1096 and #1100

**Comment by docwhomc** [comment] 2020-05-12 15:57
Duplicate of #1096.

**Closed by docwhomc** 2020-05-12 15:57 UTC
Labels: Issue type: Bug, Issue type: Towny Plugin, Server: Towny
