### ISSUE TITLE
[BUG] /t online [town name] is disabled AND /list for donators is STILL not enabled!

### ISSUE THREAD

**Issue by Magenent** [EarthMC/Issue-Tracker#560] opened 2019-05-24 06:35 UTC
Well first off you can no longer do /t online [town name], which I see no reason why, it doesn't seem broken or anything. ALSO AND VERY IMPORTANT no one can do /list or /online which also doesn't have anything bad AND its also DISABLED for DONATORS which is something that we paid for, it was on the list of perks from donating at the very least enable it for donators! Personally this was a decent reason I bought the donator rank.

**Comment by shirazmatas** [comment] 2019-05-24 06:52
It's a feature -Fix

**Comment by DasCodes** [comment] 2019-05-24 06:57
Duplicate of #560.

**Comment by shirazmatas** [comment] 2019-05-24 06:58
Eagle pls this one has more information

**Comment by DasCodes** [comment] 2019-05-24 06:58
?

**Comment by DasCodes** [comment] 2019-05-24 07:08
Everyone has access to `/t online` it's a chat bug. Temporary fix, go through a nether portal.

Ref: #518.

**Comment by Magenent** [comment] 2019-05-24 07:16
> Everyone has access to `/t online` it's a chat bug. Temporary fix, go through a nether portal.
> 
> Ref: #518.

no its not thats the nation glitch it doesn't change the fact that regular players cannot do /t online [town name]

**Comment by DasCodes** [comment] 2019-05-24 07:37
Well, I showed you in-game that it is, in fact, a chat bug, everyone has access to `/t online`. #518.

**Closed** 2019-05-24 14:12 UTC
Labels: Duplicate
