### ISSUE TITLE
[Bug] Map art created and locked then wiped by server

### ISSUE THREAD

**Issue by GodzillaHawkMama** [EarthMC/Issue-Tracker#1892] opened 2024-11-18 04:56 UTC
### Server

Aurora

### Describe the bug

[Bug] Map art created and locked then wiped by server

### To Reproduce

[Bug] Map art created and locked then wiped by server

### Expected behavior

[Bug] Map art created and locked should not be wiped by server

### Screenshots

See comments in issue #1891 please

**Comment by Kuziemekk** [comment] 2024-11-18 09:36
why make a duplicate of an issue that was already posted

**Comment by GodzillaHawkMama** [comment] 2024-11-19 12:44
> why make a duplicate of an issue that was already posted

Several reasons made it logical to do so.  1. Troubleshooting 2.It was commissioned work and carpets were still on art deck.

Cause of issue is not known. Additional data could help resolve issue for others.

Ty for asking. Any other questions?

**Comment by jkmartindale** [comment] 2024-11-22 07:39
> Several reasons made it logical to do so. 1. Troubleshooting

Making a duplicate issue offers no advantages for troubleshooting. You can just comment on the older issue, as you already did, and keep all relevant info in one place.

Making a duplicate issue adds the disadvantage of splitting relevant discussion into multiple threads, making it harder to track and troubleshoot. Well, in most cases. This specific issue doesn't even have any info worth reading, it's just "hey look at the comments on the older issue".

> Cause of issue is not known. Additional data could help resolve issue for others.

What additional data?

> Hoping to get repaired mapart to replace wiped map from mods or helper fruitloopins.

Make a ticket for anything you want looked at in a "timely" (relative) time frame. If you have loss due to a bug, it makes sense to both report the bug to get it added to the dev backlog and to make a ticket to get your specific loss remedied.

**Comment by GodzillaHawkMama** [comment] 2024-11-29 01:15
Ok -  so i'll try and delete this post

**Closed** 2024-11-29 01:15 UTC
Labels: Issue type: Bug

**Comment by GodzillaHawkMama** [comment] 2024-11-29 01:17
taking advise of jkmartindale to reduce duplicate tickets on same issue.  I didn't know making a ticket for a bug was different from making ticket in discord for refund until recently.  I'm glad issue was fixed.  Hopefully, i'll get copy of the mapart that was lost.  Thanks for all you do!
