### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by zerkillor** [EarthMC/Issue-Tracker#830] opened 2019-11-11 13:51 UTC
I have a problem withe the command for nation 
I want to do /n set capital (town) and the chat write "you don't have permissions...."

I want to change the capital of my nation
please help me

**Comment by shirazmatas** [comment] 2019-11-11 14:08
Duplicate of #813. Express your opinion on that ticket

**Closed by shirazmatas** 2019-11-11 14:08 UTC
