### ISSUE TITLE
[Bug] Some runied town is not deleted 

### ISSUE THREAD

**Issue by asyi0** [EarthMC/Issue-Tracker#1653] opened 2023-03-20 12:13 UTC
### Server

Aurora

### Describe the bug

I noticed that some town had turned into ruin was not deleted and remained for over 2 weeks.
For example, this town of niger became ruin on March 4, but still has a mayor who is still an NPC, and all permissions are turned off.
https://earthmc.net/map/aurora/?zoom=5&x=56&z=-3816&n=7,-477

I think it is due to the towny update that happened around that time.

### To Reproduce

Just check towns that mayor is npc

### Expected behavior

Ruined towns are deleted 3 days after it turned into ruin.

**Comment by Haptror** [comment] 2023-04-04 08:51
hows this a bug

**Comment by Warriorrrr** [comment] 2023-04-23 22:29
Since this seems to be a one off occurrence I'll just delete the town and close this, without a more exact way to reproduce the issue it's unlikely that this can be fixed, considering all other ruins work fine.

**Closed by Warriorrrr** 2023-04-23 22:29 UTC
Labels: Issue type: Bug, Rejected: Unfixable, Issue type: Towny Plugin
