### ISSUE TITLE
Dynmap and Voting are broken on EMC CLASSIC 

### ISSUE THREAD

**Issue by IanSpace71** [EarthMC/Issue-Tracker#411] opened 2019-03-11 20:52 UTC
The voting system and the dynamic map on EarthMc classic. The vote command does not work, and neither does dynmap, which is upsetting, as my nation needs to use it in order to colonize more lands, get gold, and explore. Ty.

**Comment by ZestyPhallus** [comment] 2019-03-11 23:24
Let classic die & focus resources on TN.

**Comment by IanSpace71** [comment] 2019-03-11 23:37
No.

**Comment by NilsNyfiken** [comment] 2019-03-12 01:15
Zesty, how dare you disrespect the server that built this community?

**Comment by Pengun78** [comment] 2019-03-12 07:48
Zestyphallus the fellow n word is doing it for his youtube series

**Comment by NeonKrby** [comment] 2019-03-12 12:21
Zesty we will commit armenian genocide against you if you dare want to delete classic

**Comment by ZestyPhallus** [comment] 2019-03-12 14:27
Nils, you’re mistaken. 
It’s the community that built this server, not the other way around.
Figuratively speaking of course. 

If someone else can provide a better argument other than preserving the barren lands of Classic so some amateur youtuber can continue creating content for their channel, then enlighten me. 

If the server doesn’t waste too many resources—by which I mean bandwith & money— from keeping Classic open, then I will apologize to you all. 

My understanding is, I’ve never seen more than 5 players on Classic at a time and all it provides is a basis for veteran players to reminisce. Ian literally has a video that proves Classic is dead. Just give it a coffin and make better memories on TN. Alternative: create a server.

Neon, if you pursue me then you prove my point as I only play Terra Nova. Instead, prove me wrong by abandoning all attachments to TN. Occupy and revive Classic MC.

**Comment by BowShot118** [comment] 2019-03-12 16:55
> Nils, you’re mistaken.
> It’s the community that built this server, not the other way around.
> Figuratively speaking of course.
> 
> If someone else can provide a better argument other than preserving the barren lands of Classic so some amateur youtuber can continue creating content for their channel, then enlighten me.
> 
> If the server doesn’t waste too many resources—by which I mean bandwith & money— from keeping Classic open, then I will apologize to you all.
> 
> My understanding is, I’ve never seen more than 5 players on Classic at a time and all it provides is a basis for veteran players to reminisce. Ian literally has a video that proves Classic is dead. Just give it a coffin and make better memories on TN. Alternative: create a server.
> 
> Neon, if you pursue me then you prove my point as I only play Terra Nova. Instead, prove me wrong by abandoning all attachments to TN. Occupy and revive Classic MC.

Only if you want us to.
Also please do remember, the people who donated, kept the server alive and called for a reset.... 
all
played 
classic.
It's a barren wasteland because of Terra Nova, why don't we close Terra Nova and focus all the server's resources onto Classic? Sounds like a great idea to me that does.

**Comment by ZestyPhallus** [comment] 2019-03-12 18:05
I’d love to not be pursued. Just a lad sharing an unpopular opinion. 

I’d also love to be wrong about Classic’s fate but I read patterns and it doesn’t look like it’s going to be revived anytime soon—or at all.

I’m sure it’s obvious that I’m a ’newfag’, which also means I don’t know about the history of Classic so thanks for the info, but I don’t understand the point. 

Are you saying the donators and community that made classic so great yet called for a reset are to blame for it’s death? Cause yeah, sounds about right.

**Comment by BowShot118** [comment] 2019-03-12 18:08
> I’d love to not be pursued. Just a lad sharing an unpopular opinion.
> 
> I’d also love to be wrong about Classic’s fate but I read patterns and it doesn’t look like it’s going to be revived anytime soon—or at all.
> 
> I’m sure it’s obvious that I’m a ’newfag’, which also means I don’t know about the history of Classic so thanks for the info, but I don’t understand the point.
> 
> Are you saying the donators and community that made classic so great yet called for a reset are to blame for it’s death? Cause yeah, sounds about right.

*Points out how not everyone wanted a reset*

**Comment by KarlOfDuty** [comment] 2019-03-23 16:29
Voting cannot be re-enabled, we will have a look at the dynmap.

**Comment by JuliusCaesar12** [comment] 2019-03-27 04:34
I remember starting Classic, in the middle of Siberia. Then, I eventually walked all the way to Africa, looking for a place to start a town. After giving up on that and traveling to California, I went all the way back to China and finally settled down in Harbin. Where I met asher1099, Vwon, and Vigiliex. That was fun, till I moved to the Chinese-Russian border to make Tanghai, where I became inactive for months. After the depression of the town being dead, I rediscovered EMC and noticed the change when I came back in January. Just some backstory, but I did notice that the dynmap is down.

**Comment by KarlOfDuty** [comment] 2019-04-07 15:04
Duplicate of https://github.com/EarthMC/EarthMC.net/issues/28

**Closed by KarlOfDuty** 2019-04-07 15:04 UTC
Labels: Bug, Duplicate, EarthMC: Classic
