### ISSUE TITLE
[Bug] Japan isn't shown in suggestion

### ISSUE THREAD

**Issue by yell52** [EarthMC/Issue-Tracker#1644] opened 2023-02-19 10:34 UTC
### Server

Aurora

### Describe the bug

When type /n ja, Japan should be shown in suggestion but isn't.
Until recently, there was Japanese_Senkaku but it has now been renamed.

### To Reproduce

Type "/n ja" in chat

### Expected behavior

Type /n ja and show Japan in suggestion.

### Screenshots

![2023-02-19_19 34 02](https://user-images.githubusercontent.com/59856902/219942721-2db630d2-d4f9-4c1b-84ad-2cf3c6a53995.png)

**Comment by Warriorrrr** [comment] 2023-02-20 18:58
I think I recall this being reported before but it was never really fixed, will need to do some investigation into what's causing this.

**Comment by yell52** [comment] 2023-03-09 08:35
It seems to be fixed.
![image](https://user-images.githubusercontent.com/59856902/223965647-48fe12ae-d03b-42fe-af3f-515e81ae17a0.png)

**Comment by Fruitloopins** [comment] 2023-03-09 08:37
very cool

**Comment by MonarchTai** [comment] 2023-03-15 21:25
Cornwall doesn't come up either. From what we have figured out, when a nation makes a nation and its name includes another nations name, it kicks the original name of N list. So, my nation Cornwall has been kicked off N list due to some people making "Cornwallis" in Canada. Hopefully the issue will be solved soon as this is very annoying.

**Comment by Warriorrrr** [comment] 2023-05-20 19:09
Will be fixed the next time we update Towny, thanks Tai for providing reproduction steps.

**Closed by Warriorrrr** 2023-05-20 19:09 UTC
Labels: Issue type: Bug, Issue type: Towny Plugin, Status: Done
