### ISSUE TITLE
[Feature] Show queue position as a boss bar

### ISSUE THREAD

**Issue by Moldytzu** [EarthMC/Issue-Tracker#1418] opened 2021-11-04 17:27 UTC
### Is your feature request related to a problem? Please describe.
The chat is being flooded with updates on queue position.

### Describe the solution you'd like
When you join, for 30 seconds it shows "You're queued for Towny" in the boss bar, it would be nice after those 30 seconds, it would show "You're X out of Y in queue" in the boss bar and it would update each 10 seconds. Also the fill value of the bar should be direct proportional with the queue position (ex.: if you're 90 out of 90 the bar would be filled to the brim, or if you're 20 out of 40 the bar would be half-filled)

**Comment by Warriorrrr** [comment] 2021-11-04 17:29
Duplicate of #1375

**Closed by Warriorrrr** 2021-11-04 17:29 UTC
