### ISSUE TITLE
A rule change for the greater good!

### ISSUE THREAD

**Issue by AureCraft** [EarthMC/Issue-Tracker#1397] opened 2021-09-07 15:04 UTC
[Feauture]
Some players join every 42 days just to keep up their town and stop active towns from developing.

The mods reccomended me to suggest this rule (change) here on GitHub:

Inactive Towns
An inactive town is
- a town with less than (X amount of people).
- capitol and only city of the nation

The claims of inactive towns can be altered in favor of active neighbouring towns. This benefits the whole server, since there would be more space for towns to expand within overpopulated areas in regions like Europe, the east border of Northern America or Asia. 

This rule change supports the development of all active towns - and so the whole server.

**Comment by Warriorrrr** [comment] 2021-10-02 16:29
Duplicate of #1229

**Closed by Warriorrrr** 2021-10-02 16:29 UTC
