### ISSUE TITLE
Adding Allied /t spawn to cut down the number of nations

### ISSUE THREAD

**Issue by lucasw2011** [EarthMC/Issue-Tracker#1046] opened 2020-04-04 07:36 UTC
I talked about adding this function to terra nova before in another ticket but it died and the problem has become much worse. On terra nova the nation price is currently over 1000 gold, after being raised from the original price. Yet nation stars flood the dynamic map 
![6F7A9B89-6903-4F50-B00B-09DAB6A5FF49](https://user-images.githubusercontent.com/45434705/78420969-0bf82980-7622-11ea-9b1e-32e338cd2dd0.jpeg)

Towns needing a way to bring people into their city are forced to choose between staying in their nation or their towns progress and usually choose their town over the nation, a new nation is purchased by a mayor gathering up enough gold to do so. With most likely a major town breaking off from one nation to create another this creates two less powerful nations in some cases creating a hostile relationship. this becomes a cycle in areas with thriving towns until the area is saturated I’ll use the north east United States as an example. This area was once all under one nation 
![ADC0C5A0-CEFA-46D8-96C0-175F165957E3](https://user-images.githubusercontent.com/45434705/78421153-84abb580-7623-11ea-8a77-cfc79e8bd39a.jpeg)
 splinters are inevitable as well as rouge nations but to the degree that we are at on emc could have been prevented by developers and staff if allied /t spawn was implemented while maintaining the claim radius. I believe if this feature was added to terra nova as it was on classic the server would be vastly improved. More players could get to their desired settling areas more towns can benefit from tourism and trade and most importantly stable and functioning one nation communities can live on earthmc again. 

On classic one nation empires thrived examples Canada, PWW, Japan, Russia, Germany.  And people could go to any allied town not just the capital. In some nations the capital wasn’t the largest town or the focal point of the nation. People also worked together for the greater good of one nation. This is a map of North America on classic 
![D67A857D-DD45-422D-A011-A0EB1C3DFFA0](https://user-images.githubusercontent.com/45434705/78421346-e1f43680-7624-11ea-8f91-a35299dea829.jpeg)
And at this point in time on classic there where less nations than the picture of The North East United States which has 10 North America on classic had 8. 

This is a problem that can easily be fixed. Not by raising nation prices and not by adding upkeep. But by adding allied /t spawn 
 I believe if this is added nations will voluntarily disband to consolidate for the greater good of their former communities. 

Please consider this for the good of the server. Thank you

**Comment by lucasw2011** [comment] 2020-04-04 07:37
If there are typos or sentences do not flow I wrote this at 3:37am please have mercy lol

**Comment by FutureLemon** [comment] 2020-04-04 14:42
No no Lucas is right for once.

**Comment by EmattpoYou** [comment] 2020-04-04 23:12
This actually is a good idea! It cuts down on nation files, which can lead for more space for the server's storage

**Comment by lucasw2011** [comment] 2020-04-04 23:31
Please if you support this cause, spread the word and help it gain traction so maybe it can actually be added

**Comment by sharkfynn1012** [comment] 2020-04-05 01:13
A different perspective through which to look at the whole allied tp argument. Before this it was mostly discussed as it made life easier and then shot down because it wasn't realistic enough. This time however it could offer performance improvements and lessen the amount of new nations or perhaps even encourage consolidation.

**Comment by suneettipirneni** [comment] 2020-04-05 05:47
@lucasw2011 copy this issue to the towny issue tracker so we can take a look at it and possibly put it on the radar.

**Comment by MineHero43** [comment] 2020-04-05 10:47
Or we could just remove /n spawn for allies altogether and make it only for nation members to teleport to their capitals. This is the direction that emc is heading in anyway and it would encourage more regional co operation, the construction of more transport links and overall give the server a more realistic feel due to the need to move around more

**Comment by lucasw2011** [comment] 2020-04-05 12:31
Minehero that would do nothing to solve the problem though the claim radius will still retain nations but it will allow them to hold more power in their respective areas people don’t want to be able to spawn to their capital they want to be able to have people come to their town to shop and show off the time and effort they’ve put into it. If people want to take power away from other nations they will have to do it by force witch I think will enhance the pvp aspect in the server and bring back a an element of War that we had on classic.

**Comment by MineHero43** [comment] 2020-04-05 13:32
> Minehero that would do nothing to solve the problem though the claim radius will still retain nations but it will allow them to hold more power in their respective areas people don’t want to be able to spawn to their capital or walk to places they want to be able to have people come to their town to shop and show off the time and effort they’ve put into it and the only way to do that is spending 1024 gold to buy a nation which is 1024 gold that could be used on their mother nation or their town or economy in general. Then if people want to take power away from other nations they will have to do it by force witch I think will enhance the pvp aspect in the server and bring back a an element of War that we had on classic.

If you want people to visit your town then make sure it’s easily accessible via transportation such as ice lines or other means. Removing n spawns for allies would take away power from big nations as they’d have to regionalise or fall into irrelevance, same for small nations.

If you want people to shop, as I said above, make sure it’s easy to access via local and regional transport. Granting more teleportation only increases the globalisation of the server and big stores running all the business. Further removing teleportation gives more power to smaller stores as they only compete with their respective region, not with the entire server

**Comment by ImperialFishy** [comment] 2020-04-05 13:46
I 100% agree with minehero. T spawns are way too op and it will ruin the server much faster because the playerbase currently is much much larger than it ever was on classic. Disabling n spawns will also make a war plugin more fun as it will be a mission to get places and wars will be fought more by relevant parties and less by people just wanting to join in the scarce action.

**Comment by lucasw2011** [comment] 2020-04-05 13:51
you guys do not understand disabling all teleportation would cripple the server completely adding allied /t spawn is far better than the alternative to having each town that boarders you and each town that boarders that town become a nation.

**Comment by ImperialFishy** [comment] 2020-04-05 14:00
Correction: disabling all tp will cripple globalization, not the server. At the moment emc has a playerbase much larger than ever and it saturates global politics and events. Promoting regionalism by removing effortless travel will fragment the playerbase to focus more on smaller areas of the world and will spread the wealth and importance. For instance, if you would like to buy a stack of diamonds and a town nearby sells them for 4g but a town on the other side of the world sells them for 1g, then in your case the person selling for 1g will always get all the trade and acquire disproportionate amounts of weatlh easily, but by removing all tp the small local trader will get his fair share of business. I believe this to be a perfect solution for a server this large and diverse.

**Comment by Lagann311** [comment] 2020-04-05 14:13
If n spawns get removed, how do you want to farm sand? How do you want to farm Terracotta clay, snow, flowers, red sand? 
No one wants to take a 20minute trip just to farm these items or to trade them.

**Comment by ImperialFishy** [comment] 2020-04-05 14:24
Im sorry that you are now the example as there are many more that feel like you do but this is one of the main grievances me and many older players have with the current situation. Its just plainly too easy do do anything and the challenge is gone for us. Everyone can achieve endgame status in a week max and this isnt how a server that stays open for about 2 years at a time should be. Players want the challenge back. Also just as a reference, in the early days of terra nova (the current world of emc) it was not uncommon for people to travel 20 minutes or more looking for certain flowers or blocks and those days were much more enjoyable.

**Comment by lucasw2011** [comment] 2020-04-05 14:47
I don’t think the server would successfully handle removing n spawn so I’m assuming that is why minehero is suggesting a reset. Which I feel is another mistake and I personally do not think I would return. Classic was much more fun and enjoyable to me and i believe it was for the people that played it I mean the few that are left anyway, most of the classic players have moved on or lost interest in the server the Canada/wabanaki community has left the server and terra nova lacks the empires that classic had: Japan, Canada, Russia. there are no strong nations anymore, Only flimsy unions Made up of other nations that could break apart with one misstep.

**Comment by lucasw2011** [comment] 2020-04-05 15:11
I don’t think the server is in need of a reset. classic didn’t need a reset it had life in it still until they announced terra nova people still played. Just because players like you have peaked doesn’t mean the server is due for a reset there is still plenty of growths and plenty of room to spare globalization through t spawn isn’t going to ruin by bringing globalization that is already here. We have to adapt the server to what the general community needs and is asking for. If we reset terra nova would have had a shorter life span than classic we cannot give up on it. Stronger nations are the key and we cannot have strong nations while towns that are not capitals are cut off from the rest of the server. The greater public does not want to travel and does not want to spend more time than needed on gathering materials by traveling to Africa something has to be added. Either allied t spawn or the claim radius needs to be removed and they need to add national t spawn that way nations could colonize and get to their colonies easier.

**Comment by MineHero43** [comment] 2020-04-05 15:15
> I don’t think the server is in need of a reset. classic didn’t need a reset it had life in it still until they announced terra nova people still played. Just because players like you have peaked doesn’t mean the server is due for a reset there is still plenty of growths and plenty of room to spare globalization through t spawn isn’t going to ruin by bringing globalization that is already here. We have to adapt the server to what the general community needs and is asking for. If we reset terra nova would have had a shorter life span than classic we cannot give up on it. Stronger nations are the key and we cannot have strong nations while towns that are not capitals are cut off from the rest of the server. The greater public does not want to travel and does not want to spend more time than needed on gathering materials by traveling to Africa something has to be added. Either allied t spawn or the claim radius needs to be removed and they need to add national t spawn that way nations could colonize and get to their colonies easier.

Classic was completely dead, TN has done wonders for EarthMC, I don't know how one can disagree there. The server is gridlocked, stale and in limbo. https://www.reddit.com/r/EarthMC/comments/fvcdg0/its_time_for_a_reset/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

I repeat what Fishy said above about the server being too easy and not much of a challenge. Ice lines are extremely efficient, don't be lazy, get a pick and some ice. People prefer challenges much more than just having everything handed to them with teleportation. Globalization is bad for the server, it's why the nation radius was added. Anything I say would just be repeating what I've said previously

**Comment by nipdip** [comment] 2020-05-05 21:36
This will slow the production of new nations, sure, but after paying the gold to make a nation in the first place, I doubt they will just disband.

**Comment by MarangaI** [comment] 2021-05-15 23:36
sus

**Comment by Prismary** [comment] 2021-11-07 21:12
As the issue is not nearly as bad anymore nowadays I'll close this for being outdated.

**Closed by Prismary** 2021-11-07 21:12 UTC
Labels: Server: Towny, Issue type: New Feature, Issue type: Towny Plugin
