### ISSUE TITLE
[Feature] towny war

### ISSUE THREAD

**Issue by Pengun78** [EarthMC/Issue-Tracker#495] opened 2019-04-25 10:51 UTC
add towny war my brothers

**Comment by Ultil0l** [comment] 2019-04-25 11:48
add towny war my brothers

**Comment by NeonKrby** [comment] 2019-04-25 12:09
add wowny tar by mrothers

**Comment by unown006** [comment] 2019-04-25 13:23
Right Before Terra Nova launched Fix said Creator from Hell was working on some system somewhere not sure if that's still the case

**Comment by Pengun78** [comment] 2019-04-25 14:11
probably not i mean do u remember the dungeons trailer and do u think that will ever happen

**Comment by watergod1234** [comment] 2019-04-25 15:35
#444

**Comment by Aitonater** [comment] 2019-04-26 13:30
yeah karl has already said no to war lots and lots of times: here and on reddit. But maybe to war days.

**Comment by Twitchyyy** [comment] 2019-04-26 17:57
all war needs to be is PvP mutually enabled for the warring nation towns

**Comment by Aitonater** [comment] 2019-04-26 18:01
Karl has said no because no working war plugin exists and he doesnt have time to make one

**Comment by Pengun78** [comment] 2019-04-26 18:13
We need creatorfromhell for this😤😤

**Comment by Ultil0l** [comment] 2019-04-26 21:12
idc that Karl said no

**Comment by Aitonater** [comment] 2019-04-26 21:20
Are you going to do the coding for it Util?

**Comment by Ultil0l** [comment] 2019-04-26 21:35
If I knew how to code ~~Unlike Karl~~ I would do it

**Comment by KarlOfDuty** [comment] 2019-04-26 22:50
Duplicate of #444

**Closed by KarlOfDuty** 2019-04-26 22:50 UTC
Labels: Duplicate

**Comment by Pengun78** [comment] 2019-04-27 07:54
No #444 is war days
