### ISSUE TITLE
Return Prompt for /nick Shows IGN Instead of the Nickname typed.

### ISSUE THREAD

**Issue by Xanereth** [EarthMC/Issue-Tracker#1554] opened 2022-07-04 04:19 UTC
As the title says, the return prompt for /nick || /nickname will show your IGN username instead of the nickname you typed. For example:
I am a premium player. My username is Xanereth
I type the following into chat: /nick Test || /nickname Test
Return prompt will then send the following: Your nickname is now Xanereth.
The text should say: Your nickname is now Test.
I believe the nick command is taking the username of the player for the return prompt rather than the variable at the end of the command which would be the nickname the player chose.  This might be confusing for first time Premium users but otherwise it is non-problematic gameplay wise.

Nonetheless, /nick serves it's main function. The return prompt does not.

**Comment by Warriorrrr** [comment] 2022-07-04 16:40
Essentials (especially the /nick command) has been acting strange for a while now, other than updating to the latest version, there's not much I can do to fix it. Nova and aurora are only 22 builds behind, not sure if anything related to nickname was changed recently.

**Comment by Warriorrrr** [comment] 2022-07-07 20:35
This seems to be caused by essentials' change-displayname option being set to false

**Comment by Warriorrrr** [comment] 2022-07-12 11:18
Fixed by https://github.com/EssentialsX/Essentials/pull/4980

**Closed by Warriorrrr** 2022-07-12 11:18 UTC
Labels: Issue type: Bug
