### ISSUE TITLE
Lack of ink sacks, possibly add a way of actually obtaining them?

### ISSUE THREAD

**Issue by MineHero43** [EarthMC/Issue-Tracker#160] opened 2018-11-20 23:03 UTC
Like Dark Oak previously, it is currently almost impossible to obtain ink sacks more specifically a large amount of them. Squids don't seem to be spawning and they're the only real way of obtaining them at the moment.

I think it would be beneficial if there was maybe a villager added somewhere like on classic who sells ink sacks for a cheap amount of gold, seeing as we had the same issue on emc classic with ink sacks.

**Comment by BowShot118** [comment] 2018-11-20 23:11
That is very true. Like on Classic, Ink is incredibly hard to get. There also seem to be a lack of other sea creatures spawning in their biomes. (Tropical Fish, Dolphins)

**Comment by Arganog** [comment] 2018-11-20 23:13
I think it would be ideal if we could increase mob spawning in general- I feel like I haven't seen any non nether mobs in a while

I don't know if adding a villager that sells ink like on classic would be possible without a /spawn location to place it

**Comment by Arganog** [comment] 2018-11-20 23:44
#154

**Comment by KarlOfDuty** [comment] 2018-11-23 16:19
Duplicate of #154

**Closed by KarlOfDuty** 2018-11-23 16:19 UTC
