### ISSUE TITLE
Ice Roads

### ISSUE THREAD

**Issue by B2315** [EarthMC/Issue-Tracker#1573] opened 2022-08-07 16:15 UTC
On Terra Nova, in my opinion, there was an issue with the amount of ice roads that are above ground. I think that since the map has had a fresh start we should make the most of it and implement some changes to help keep the map looking somewhat natural and good looking for the future.

To do this I suggest we put some kind of restrictions on ice roads, such as making it so that they have to be underground. With haste being as cheap as it is it won't make underground ice roads much more difficult.

Not only are they an eyesore, they sometimes restrict access by boat. This will inevitably lead to many passers by breaking a hole through it (look at the Atlantic highway on Terra Nova).

An alternate idea would be to make sure that every mayor nearby agrees with the creation of an above ground ice road but I understand that might be more complicated.

This addition could also be applied to the various bridges that go across open oceans.

![iceroad](https://user-images.githubusercontent.com/98907620/183300299-9fe25c79-c5c5-4fe2-89ad-74e7b344248c.png)

**Comment by docwhomc** [comment] 2022-08-07 22:52
I've been working on coordinating a construction effort in the nether. Though we could add overworld infrastructure if folks are dead set on putting it in the overworld. Either way, it's important to coordinate construction to avoid issues (e.g., two ice roads at slightly different levels interesting each other, requiring one to divert around the other).

Here's the discord: https://discord.gg/v6tfPKpadk

**Comment by docwhomc** [comment] 2022-08-07 23:35
Duplicate #1527

**Comment by Warriorrrr** [comment] 2022-09-04 13:24
Closing as duplicate of the issue mentioned above.

**Closed by Warriorrrr** 2022-09-04 13:24 UTC
