### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RedstoneFox441** [EarthMC/Issue-Tracker#1307] opened 2021-01-28 23:41 UTC
### Server

EarthMC towny
### Describe the bug

After the server rolled-back at 6:30 PM, my map art disappeared. All that is left is the item frames they were in. It should not have been rolled back as I got the map art 2 days ago.

### To Reproduce

1. A server roll-back occurs.
2. I have no idea what happened next.

### Expected behavior

The map art should have still existed.

### Screenshots

How do I show something that does not exist anymore?

### Additional context

In areas around where the map art disappeared some glitches were occurring due to the roll-back

**Comment by Warriorrrr** [comment] 2021-05-11 20:28
Duplicate of #1249

**Closed by Warriorrrr** 2021-05-11 20:28 UTC
Labels: Issue type: Bug
