### ISSUE TITLE
Towny Chunk Claiming Bug

### ISSUE THREAD

**Issue by Nalasleafheart** [EarthMC/Issue-Tracker#1100] opened 2020-05-07 05:48 UTC
**Server**
Towny

**Describe the bug**
Unable to claim chunks where I previously was able to about a month ago. Nothing has been changed regarding town claims around me.

**To Reproduce**
I try to claim another chunk for my town, "This area is too close to another homeblock" I'm not creating another town so this error shouldnt be popping up

**Expected behavior**
Normally it allows me to claim these chunks

**Screenshots**
Red is where I am trying to claim, west is the ocean. 
![claiming](https://user-images.githubusercontent.com/22863875/81258612-eaa4a780-8fea-11ea-929b-ed350f87e2f7.png)

**Additional context**
This happened recently to someone else in Korea, it was apparently fixed the other day for them, I'm unsure if this is a bug or issue for all of Korea or a recent setting changed in towny that bugged some chunks. 
Below is another image of the situation, red is what was recently fixed for another town in my nation, purple is what is bugged currently for me from what I know 
![bugged](https://user-images.githubusercontent.com/22863875/81258902-90581680-8feb-11ea-8dc0-bc6a5abcfb5f.png)

**Comment by DTHMASTER** [comment] 2020-05-07 07:26
Same thing is happening to me, I guess it is to prevent claim blocking?

**Comment by Nalasleafheart** [comment] 2020-05-07 20:44
> Same thing is happening to me, I guess it is to prevent claim blocking?

idk, someone fixed the chunks up north east so it could be a bug

**Comment by riri2010** [comment] 2020-05-10 01:23
![Capture](https://user-images.githubusercontent.com/50254131/81488762-0c3ba400-9222-11ea-8394-1e833f833a5d.PNG)
I have the same issue. there is no reason I shouldnt be able to claim towards the south-east. I have permission and border agreements with all 4 towns.

**Comment by docwhomc** [comment] 2020-05-12 15:56
This appears to be a duplicate of #1096.

**Closed by docwhomc** 2020-05-12 15:56 UTC
Labels: Issue type: Bug, Issue type: Towny Plugin, Server: Towny

**Comment by Nalasleafheart** [comment] 2020-05-12 17:59
> This appears to be a duplicate of #1096.

#1096 was fixed, this is why I made another bug report, so my issue can be fixed as well.

**Comment by riri2010** [comment] 2020-05-12 18:04
it needs to be fixed across the whole server. there are many others having this same issue. Nalasleafheart I suggest we both leave a comment on #1096 to show interest since #1100 is now closed

**Comment by Nalasleafheart** [comment] 2020-05-12 18:05
> it needs to be fixed across the whole server. there are many others having this same issue. Nalasleafheart I suggest we both leave a comment on #1096 to show interest since #1100 is now closed

#1096 was resolved though.
