### ISSUE TITLE
REGARDING THE WAITING ROOM

### ISSUE THREAD

**Issue by BunbunToast** [EarthMC/Issue-Tracker#473] opened 2019-04-19 03:06 UTC
I would like something to do other than fondle my balls for 2 hours, waiting to get into the game.

What if we had a 1000x1000 world to fuck around in while we wait? It doesn't even need any rules. Just something to do.

OH, OH, OH!! EDIT!!
ADD ELYTRAS IN THE WAITING ROOM!!

**Comment by xParadoxical69** [comment] 2019-04-19 04:18
There are 3 parkours, but they are just awful and boooooring...

1000x1000 PVP world would be just beautiful. There could be pvp kits, that's everything needed. It would be awesome and much more interesting to play such a thing while waiting to join the Towny server!
Also players could go back from the Towny to pvp lobby with some command, if they would want to play it instead of Towny. Towny would be of course still the main server, pvp world should be still a lobby, but just 1000x1000 and with pvp.

**Comment by xParadoxical69** [comment] 2019-04-19 04:23
Also please do not double-create issues. You should close now #472

**Comment by KarlOfDuty** [comment] 2019-04-19 19:32
Duplicate of #472

**Closed by KarlOfDuty** 2019-04-19 19:32 UTC
Labels: Duplicate
