### ISSUE TITLE
PLOT CLAIM BUG

### ISSUE THREAD

**Issue by Nevertime06** [EarthMC/Issue-Tracker#1059] opened 2020-04-14 15:21 UTC
**Server**
EMC

**Describe the bug**
Hello,
I have a question. Yesterday I claimed the two plots (in red on the image). The waiter did not answer me as usual, he said "Plot have been claimed" in red. I do have my 32g that came out of the bank, but the two plots were not added to the city.
Do you have an idea ?
Where did the 32Gold go?

**Expected behavior**
Hello,
I have a question. Yesterday I claimed the two plots (in red on the image). The waiter did not answer me as usual, he said "Plot have been claimed" in red. I do have my 32g that came out of the bank, but the two plots were not added to the city.
Do you have an idea ?
Where did the 32Gold go?

**Screenshots**

![EMCPLOTS](https://user-images.githubusercontent.com/63657850/79242022-11504200-7e74-11ea-96d3-950d4a0a0b83.jpg)

**Additional context**

I already lost 32g because nation are not available on dyn map and spain was not satisfy about two plots (declaimed after...).
So 64G is so much to lost and the server is too slow for mining (ping!).
Can you do something please ?
Thank you so much. :)

**Comment by FutureLemon** [comment] 2020-04-14 18:41
Duplicate of #1056

**Comment by Nevertime06** [comment] 2020-04-14 21:51
I don't know, i'm not the same person has the #1056.
So can you make something about that ?

**Comment by Nevertime06** [comment] 2020-04-14 22:45
<img width="511" alt="CLAIM2" src="https://user-images.githubusercontent.com/63657850/79280969-116f3280-7eb2-11ea-85d4-9aa6c61cade5.png">

3 hours of Farm to have gold back, i try again and has you can see, again 16 Gols losted ! Total : 48 Gold ! 

Please, someone can find a solution ? 
My 3 friends join server after my demonstration and paid premium queue too but we lost 48g and we don't arrive to claim two plot in my first picture but server eat gold :p 

Thank you by advance,
Nevertime.

**Comment by Nevertime06** [comment] 2020-04-15 00:47
???

**Comment by jkmartindale** [comment] 2020-04-15 02:16
If you want a faster response, join the [support Discord server](https://discord.gg/EZBYmpp) and start a support ticket by typing `-new`

This is a place to report bugs with the server admins/developers as the primary audience, so response times aren't as fast here as they are on the support server.

**Comment by FutureLemon** [comment] 2020-04-15 14:37
> I don't know, i'm not the same person has the #1056.
> So can you make something about that ?

This is a duplicate, both of you describe the same bug. Like jkmartindale said if you want a refund make a ticket in the support ticket.

**Comment by Cactusinapumpkin** [comment] 2020-04-15 22:32
This should be fixed now

**Closed** 2020-04-16 12:45 UTC

**Comment by Nevertime06** [comment] 2020-04-16 15:33
Nice, i try again to buy one of them plot and it's look like ok.
Now i hope support discord server could remburse me because 48Gold is too much :)
Have a nice day ;-)
