### ISSUE TITLE
Make mob heads (creeper, skeleton, zombie) obtainable again

### ISSUE THREAD

**Issue by STGWinteam** [EarthMC/Issue-Tracker#1565] opened 2022-07-29 19:03 UTC
### Is your feature request related to a problem? Please describe.

Powder Snow and Mob Heads are unobtainable on EMC because there's no weather here. Powder Snow is very useful thing for traps and mob farms. Creeper Head can be used to create a banner pattern.

### Describe the solution you'd like

Adding a custom craft for powder snow and mob heads either turning on the thunderstorm and rain sometimes.

**Comment by asyi0** [comment] 2022-08-01 16:16
It would be interesting weather change added again.

**Comment by docwhomc** [comment] 2022-08-07 23:29
Partial duplicate of #1564

**Comment by Warriorrrr** [comment] 2023-01-07 09:10
Mob heads should be obtainable now that weather exists again.

**Closed by Warriorrrr** 2023-01-07 09:10 UTC
Labels: Status: Done
