### ISSUE TITLE
[BUG] Shift-clicking to move multiple stacks of items at a time does not work.

### ISSUE THREAD

**Issue by Dachius** [EarthMC/Issue-Tracker#1380] opened 2021-07-31 17:43 UTC
### Server
Towny

### Describe the bug
Shift-clicking to move multiple stacks of items at a time does not work. Only one stack will move as if the player was not holding an item, and the rest which should have moved will flicker.

### To Reproduce
1. Place numerous stacks of items in a chest, and clear your inventory.
2. Pick up one of the stacks via clicking on it.
3. Hover over one of the other stacks, hold shift, and then double click on it.

### Expected behavior
Stacks of the shift + double-clicked item (The one on which you click, not necessarily the one you are holding) should be transferred to your inventory until there are no more items or until your inventory is full.

### Additional context
I expect this is related to an anti-cheat plugin that attempts to deal with inventory management mods. Scroll down to 4th paragraph of the Shift section on [this](https://minecraft.fandom.com/wiki/Controls#Non-configurable_controls) page for information on this feature.

**Comment by jkmartindale** [comment] 2021-08-01 00:50
I haven't been able to reproduce this (I'm assuming what you're describing isn't a vanilla mechanic, because the page you linked says only one stack gets moved at a time), but I don't think it's related to anti-cheat and don't think it's something that can be easily fixed.

Whenever you do something (including move items around in inventories), your client sends data to the server, the server checks it, and then sends confirmation back to your client. They have to stay in sync for each action.

The server is under heavy load, so when your client sends a lot of actions at once the server doesn't always keep up and it'll drop some of the client messages. This is why not all your stacks get transferred, or seem to be duplicated on the client side.

I've run into the same thing with a mod that swaps all your armor slots at once with an armor stand, and the same thing happens (but in the opposite direction) when you're haste mining and run into ghost blocks.

**Comment by Dachius** [comment] 2021-08-02 15:20
It's a little known vanilla feature- [here's a screenshot](https://i.imgur.com/Us4jLwM.png) containing that section of the text outlined in red. [Here's a video](https://www.youtube.com/watch?v=UgtoJ4ihhbQ) which might help.

**Comment by jkmartindale** [comment] 2021-08-03 05:27
ahh rip, turns out I can't read lol

I was actually able to get it to work on the server just now, so I'm guessing it was a lag thing.

**Comment by Dachius** [comment] 2021-08-06 21:25
The issue persists on my side. I've checked several times to see if it goes away. I also haven't seen this issue on servers on which my ping is much lower.

**Comment by jkmartindale** [comment] 2021-08-13 17:43
Interesting, I just tried it with vanilla 1.17.1 and couldn't get all the stacks to move, but immediately switching back to vanilla 1.16.4 I was able to just fine

**Comment by Warriorrrr** [comment] 2022-01-10 09:08
I'm pretty sure this issue was related to an issue in viaversion, I haven't noticed any issues like this after the server updated from 1.16 -> 1.17.

**Closed by Warriorrrr** 2022-01-10 09:08 UTC
Labels: Issue type: Bug
