### ISSUE TITLE
Help Mapart, bring back carpet duping

### ISSUE THREAD

**Issue by Fedrerr** [EarthMC/Issue-Tracker#1610] opened 2022-12-20 01:00 UTC
### Is your feature request related to a problem? Please describe.

During Terra Nova mapart was one of the most consistent things in time. Many maparts appeared every month which helped the economy, with many mapart stores around the world. They were not only used for art but for other purposes as well. This was mostly thanks to carpet duping being legal and possible. Now with almost 10 months of Terra Aurora I find it hard to see new mapart, or at least as much as I did during Terra Nova and for anyone trying to get into mapart is hard as well, as now you need to get lots of wool for the carpets. There used to be communities around maparting, people created games like chess with it, music album covers, museums, art, tributes, etc. 

### Describe the solution you'd like

Carpet duping is currently patched, so the easiest way to solve this is to bring it back, as well as making it legal. Carpets are usually not sold in shops so it wouldn't be a problem for the EarthMC economy, who would actually benefit from it due to the increasing ammount of mapart entering the market.

**Comment by BreachDGates** [comment] 2023-01-06 11:49
What about a custom recipe?
1 carpet = 64 carpets (16 custom recipes, one for each color)
Doesn't cause lag

**Comment by Fruitloopins** [comment] 2023-01-06 18:53
Carpet recipe sounds good until people use it to drop thousands of carpets at your n spawn every day

**Comment by Aylywyn** [comment] 2023-01-06 19:02
Two 16-pixel blocks of wool normally make 3 1-pixel carpets.  Not that one should expect any realism but a custom recipe to give 2 Wool = 32 Carpet would make sense.  Still moderately prone to moderate abuse as above, but WAY less so than allowing a pure duping "solution".

**Comment by CorruptedGreed** [comment] 2023-12-10 10:52
Duplicate of #1334

**Closed by CorruptedGreed** 2023-12-10 10:52 UTC
