### ISSUE TITLE
Revoking town invites is broken 

### ISSUE THREAD

**Issue by MineHero43** [EarthMC/Issue-Tracker#936] opened 2020-02-11 14:59 UTC
You can only send a maximum of 35 invites to your town before having to wait a while for it to reset. Usually this could be avoided as previous invites could be revoked with /t invite -playername but that no longer works. 

Could either the revoke function be fixed or the maximum invites of 35 increased/removed?

**Comment by docwhomc** [comment] 2020-02-12 02:08
Duplicate of #914

**Closed** 2020-02-20 20:19 UTC
Labels: Rejected: Duplicate
