### ISSUE TITLE
[BUG] Plot Permissions

### ISSUE THREAD

**Issue by HyperDjole07** [EarthMC/Issue-Tracker#1406] opened 2021-10-01 17:57 UTC
### Server

EarthMC.net

### Describe the bug

Plot permission, if you set your plot perm to build for let's say friends, your friends still can't access given permissions.

### Expected behavior

Given permission shall work.

### Screenshots

![image](https://user-images.githubusercontent.com/91753879/135665565-683a3648-c3c1-4216-b679-734ed788de87.png)
![image](https://user-images.githubusercontent.com/91753879/135665702-3a574402-bd78-4f8b-a2e9-51f5c397b91b.png)

### Additional context

No additional context, everything explained.

**Comment by Warriorrrr** [comment] 2021-10-02 16:18
Show me the output of /plot perm in that plot

**Comment by Warriorrrr** [comment] 2021-10-02 16:46
Nevermind, duplicate of #1405

**Closed by Warriorrrr** 2021-10-02 16:46 UTC
Labels: Issue type: Bug, Status: Awaiting OP's Comment

**Comment by to-kamimura** [comment] 2021-10-04 15:41
@Warriorrrr 
https://github.com/EarthMC/Issue-Tracker/issues/1405
https://github.com/EarthMC/Issue-Tracker/issues/1406

It seems that these issues have not been resolved yet.
The residents of the town I belong to at Earth MC are still can't access given permissions.
Is this bug fix not yet applied to the EarthMC server?

**Comment by Warriorrrr** [comment] 2021-10-04 15:45
> Is this bug fix not yet applied to the EarthMC server?

No, not yet apparently.

**Comment by to-kamimura** [comment] 2021-10-04 15:52
@Warriorrrr 
Thank you for the answer.
Do you know when this bug will be resolved?

**Comment by melty-muscle** [comment] 2021-10-04 20:45
I also ask a question too.
If this bug hasn't been resolved yet, why are you closed these issues?
https://github.com/EarthMC/Issue-Tracker/issues/1405 https://github.com/EarthMC/Issue-Tracker/issues/1406

I think that it's possible another issue with the same content will be opened.
because many players are facing the same problem right now.
Does EarthMC's Administrators recognize that this bug is serious?
All residents can't do anything in their own town now.
