### ISSUE TITLE
New shop plugin

### ISSUE THREAD

**Issue by TypicalFernie** [EarthMC/Issue-Tracker#112] opened 2018-11-08 18:58 UTC
We really need a new shop plugin like the one from classic. Yea the current one looks cool and all but its only useful for items worth more than 1 gold. The plugin doesn't allow you to sell more than 1 item for 1 gold. So for example, we can't sell 64 clay for 1 gold. Adding a new plugin that will allow us to do this will make it much better than having to do trades in person.

**Comment by KarlOfDuty** [comment] 2018-11-08 19:02
Duplicate of #99

**Closed by KarlOfDuty** 2018-11-08 19:02 UTC
Labels: Duplicate
