### ISSUE TITLE
[Bug] Claiming Land

### ISSUE THREAD

**Issue by Fjolnir5** [EarthMC/Issue-Tracker#1109] opened 2020-05-10 17:58 UTC
**Server**
Towny

**Describe the bug**
Cant claim due to other towns home blocks being too close

**To Reproduce**
/t claim
see screenshot

**Expected behavior**
I should be able to claim land 

![image](https://user-images.githubusercontent.com/65129160/81506645-bb927c80-92ef-11ea-8128-17c240496af7.png)

I made a ticket about this and they said to report it here since it is a bug. i just want to get the claims so I can finish this mapart platform. forgive me if i did anything wrong ive never used github

**Comment by jkmartindale** [comment] 2020-05-10 19:19
tbh you didn't need to file a new bug report, other people have reported the same thing at #1101, #1100, and #1096

**Comment by docwhomc** [comment] 2020-05-12 15:57
Duplicate of #1096.

**Closed by docwhomc** 2020-05-12 15:57 UTC
Labels: Issue type: Bug, Issue type: Towny Plugin, Server: Towny
