### ISSUE TITLE
Breaking sign shops & sign shop chests

### ISSUE THREAD

**Issue by FutureLemon** [EarthMC/Issue-Tracker#686] opened 2019-08-05 01:48 UTC
I cannot break sign shops anymore owned by other people that have quit the server. You're also unable to open chests of shops that are out of stock this means I cannot refill them either.

**Comment by VoiD7965** [comment] 2019-08-07 19:59
Same problem

**Comment by KarlOfDuty** [comment] 2019-08-08 20:57
Duplicate of #685

**Closed by KarlOfDuty** 2019-08-08 20:57 UTC
