### ISSUE TITLE
[BUG] Cannot Make Concrete

### ISSUE THREAD

**Issue by Zephireosia** [EarthMC/Issue-Tracker#395] opened 2019-03-03 22:07 UTC
**Server**
Earthmc.net

**Describe the bug**
When I put concrete powder next to water it turns to concrete, BUT, when I mine it, it reverts itself back to the concrete powder state.

**Comment by PoppyK** [comment] 2019-03-03 22:33
duplicate of #384.  You can read it here:  https://github.com/EarthMC/Issue-Tracker/issues/384

**Closed by PoppyK** 2019-03-03 22:33 UTC
