### ISSUE TITLE
Blue donor Prio

### ISSUE THREAD

**Issue by BowShot118** [EarthMC/Issue-Tracker#511] opened 2019-05-04 13:20 UTC
Frost Donators don't have priority over Priority queue despite the originally higher purchase price. Was this deliberate or do you not love us? :(

![2019-05-04_14 18 27](https://user-images.githubusercontent.com/44571571/57179636-b8acb280-6e77-11e9-87a5-dde83e9bc40a.png)

**Comment by Pengun78** [comment] 2019-05-04 13:29
because he wants money money

**Comment by CloakedEagle** [comment] 2019-05-04 15:21
I think the priority between donors and priority holders are the same.

**Comment by NeonKrby** [comment] 2019-05-04 15:30
nobody loves u pock
xd

**Comment by WhitPlayzYT** [comment] 2019-05-04 20:53
How I think priority should work:
Priority/Yellow Donator - Starts at position 6 in queue
Purple Donator - Starts at position 4 in queue
Frost Fade/Blue Donator - Starts at position 2 in queue

**Comment by CloakedEagle** [comment] 2019-05-04 20:57
And everyone else would start at position 1. 🤔

**Comment by WhitPlayzYT** [comment] 2019-05-04 21:07
everyone else would start at the last position @CloakedEagle

**Comment by FixTheAdmin** [comment] 2019-05-07 09:36
It's a bug, sorry about that. It will be fixed sometime this week.

**Comment by FixTheAdmin** [comment] 2019-05-07 10:02
Is anyone else able to confirm this issue? I've not been able to reproduce it.

**Comment by alekb1** [comment] 2019-05-07 10:34
I'm purple donator, and this has happened a couple of times to me, here is how i understand it:
So when you join as donator, you're placed in the queue as number 6. If another donator then joins before you move up to number 5, you'll be kicked back to number 7, then another joins and you're kicked back to number 8. I've experienced it a couple of times, and every time i just relog, as i'm then placed as number 6 again. This rarely happens, and only really at peak hours of the server.

**Comment by alekb1** [comment] 2019-05-09 21:17
![image](https://user-images.githubusercontent.com/47500274/57487333-94eecf80-72b0-11e9-91a4-cd95dcb77b99.png)

**Comment by volzeran** [comment] 2019-05-09 21:33
Issa bug. /leavequeue and rejoin often fixes it for me

**Comment by DasCodes** [comment] 2019-06-04 18:48
This has been fixed. @BowShot118.

**Closed by DasCodes** 2019-06-04 18:48 UTC
Labels: EarthMC: Towny
