### ISSUE TITLE
Invitation to town

### ISSUE THREAD

**Issue by zerkillor** [EarthMC/Issue-Tracker#842] opened 2019-11-29 16:47 UTC
hello it's been 3 days since I can not invite a member to my town on earthmc towny

I am making  /t invites [player] and /t add [player]
And the chat writes 
![JPEG_20191129_172856](https://user-images.githubusercontent.com/57627920/69882383-46e2fd00-12d0-11ea-90d5-0ecb9912cd92.jpg)

**Comment by KarlOfDuty** [comment] 2019-12-03 23:45
Duplicate of #839

**Closed by KarlOfDuty** 2019-12-03 23:45 UTC
