### ISSUE TITLE
[Recipe] Crying Obsidian 

### ISSUE THREAD

**Issue by unown006** [EarthMC/Issue-Tracker#1723] opened 2023-10-24 10:48 UTC
### Is your feature request related to a problem? Please describe.

Unable to obtain crying obsidian with out using gold to trade with piglins
crying obsidians drop rate is 8.7% to get 1-3 per gold ingot trade

### Describe the solution you'd like

Add A custom Recipe that cost 8 obsidian and one ghast tear that produces 8 crying obsidian

8 obsidian placed like you would craft a chest with a ghast tear in the middle 

### Additional context

Adding this not only would give players access to use a cool new block in builds but also able to craft respawn anchors to travel and explore in the neather

**Comment by Veyronity** [comment] 2023-10-24 10:55
will crash the market, that 2g per cost will now be 1g per 2, over 75% loss for anyone who invested in it

Pass

**Comment by CorruptedGreed** [comment] 2023-10-24 11:53
Duplicate of #1668

**Closed** 2023-10-24 11:53 UTC
