### ISSUE TITLE
Add Nation Upkeep to EarthMC

### ISSUE THREAD

**Issue by anixrazr** [EarthMC/Issue-Tracker#1744] opened 2023-12-12 00:44 UTC
### Is your feature request related to a problem? Please describe.

Overclaim was added to allow more active players to take control of land. However, for nations, once you make one, there is nothing stopping you from holding it forever. All you need to do is log in once a month.

A nation should be something more than just a small town with an inactive mayor holding a particular nation name like “USA” forever. It should instead be more like a true nation, a collection of towns and an active community

### Describe the solution you'd like

Enable nation upkeep, which I believe is in the towny config. I personally would like nation upkeep to cost 10 gold a day, but any number is better than nothing. 

This would force players to think twice before making a nation, and force them to invest something into their nation indefinitely, which would help prevent them from sitting on a nation forever with no incentive to put effort into it

### Additional context

It is possible for someone to just dump 2,000 gold into their nation and remain inactive, but at the very least it would be a gold sink. It would be ideal if a nation also had a minimum player or town requirement but that isn’t what this suggestion is about

-Collaboration with 32Dan

**Comment by patagoniapat** [comment] 2023-12-12 01:02
agree

**Comment by unown006** [comment] 2023-12-12 01:44
Would require a refund period

**Comment by Awuzup007** [comment] 2023-12-12 01:45
Yes

**Comment by Joixe776** [comment] 2023-12-12 02:08
yes we need this

**Comment by Pengun78** [comment] 2023-12-12 02:09
yes we need this

**Comment by Mikeyreza** [comment] 2023-12-12 02:55
pointless addition, dont need

**Comment by deafkite42** [comment] 2023-12-12 06:12
it could go into a "dormant" state after failing to pay where certain things are disabled before finally falling to give a bit of a grace period so that nations don't fall before the owner even realizes

**Comment by quarox777** [comment] 2023-12-12 08:23
yes, mich better than overclaim nonsense

**Comment by 32danny** [comment] 2023-12-12 12:49
I support this

**Comment by 32danny** [comment] 2023-12-12 12:50
> yes, mich better than overclaim nonsense

Well this is suggesting nation upkeep on top of Overclaim, nowhere does this post say "get rid of Overclaim"

**Comment by 32danny** [comment] 2023-12-12 12:50
> it could go into a "dormant" state after failing to pay where certain things are disabled before finally falling to give a bit of a grace period so that nations don't fall before the owner even realizes 
> 
> 
> 
> although there would have to be some mechanism to prevent people from abusing this mechanic to avoid a lot of upkeep

This could work too, but can't people just monitor their nation balance?

**Comment by 32danny** [comment] 2023-12-12 12:50
> Would require a refund period

Maybe but there's already been so much gold refunded because of Overclaim

**Comment by UnitiveBog** [comment] 2023-12-12 13:27
For the nations that are either small, lazy, inactive or dont have a good source of income, a 10g per day upkeep for nations could be unsustainable, Something like 4g to 6g per day is sustainable for most. But if the intention is to stop nations from claiming too much of the map then this will work fine

**Comment by 8set** [comment] 2023-12-13 12:18
I disagree completely with this concept. The fact that nations cost 2048g to make on their own is enough. This would make nations even more of a burden on people's shoulders.

**Comment by Proserrr** [comment] 2023-12-13 13:45
> I disagree completely with this concept. The fact that nations cost 2048g to make on their own is enough. This would make nations even more of a burden on people's shoulders.

To make a nation yes, but how many people bought their nation m for a few hundred? Recently i middlemanned a nation transfer for 200g. The issue is there is no gain from disbanding a nation. Those who don’t want one anymore just sell and pass it on. An endless cycle which is why the number of nations has never really decreased

**Comment by Proserrr** [comment] 2023-12-13 13:49
I think 10g/day universally is too high. Either reduce it to something like 5, or have it decrease depending on a certain metric (more towns/residents = less upkeep)
I think a short, at least partial refund period wouldn't be too harmful.

**Comment by CorruptedGreed** [comment] 2023-12-18 01:28
Denied by Fix, due to "dormant nations already being addressed by overclaim"
![image](https://github.com/EarthMC/Issue-Tracker/assets/47507792/6b80c534-d2a6-4a52-8a09-86b440f8c835)

**Closed** 2023-12-18 01:28 UTC
Labels: Issue type: Game Mechanic, Issue type: Towny Plugin
