### ISSUE TITLE
Allow players to make uncopyable map art

### ISSUE THREAD

**Issue by asyi0** [EarthMC/Issue-Tracker#1587] opened 2022-10-04 14:09 UTC
### Is your feature request related to a problem? Please describe.

It discourage map art artists that map arts can be easily copied by anyone and resold as pirated copies by others.
Therefore, the creators should be able to make map art uncopyable  if they wish. ( Not all map art should be uncopyable )

### Describe the solution you'd like

There is a plugin that makes map art uncopyable with the `/art lock` command.
https://github.com/Namako771/MapCopyright

If this applies, this problem can be solved.
I hope you will consider this one.

**Comment by Warriorrrr** [comment] 2022-10-04 17:20
Duplicate of #1438

**Closed by Warriorrrr** 2022-10-04 17:20 UTC
